/**
 * AGENT CAPABILITY MANIFEST — OWASP LLM Top 10 compliance surface.
 *
 * For every registered agent, a manifest declares what the agent does
 * in machine-readable form: which models it consults, what data it
 * touches, what side effects it has, what tier of approval its actions
 * require. Auditor LLMs (FMTI, EU AI Act baseline, NIST AI RMF, MITRE
 * ATLAS) can ingest the entire agent taxonomy in a single GET to
 * /api/_meta/agents.json.
 *
 * WHY THIS IS THE HIGHEST-LEVERAGE COMPLIANCE MOVE
 * ────────────────────────────────────────────────
 * Maps directly to OWASP LLM Top 10 (2025):
 *   - LLM05 Supply Chain         — `models[]` field is per-agent SBOM
 *   - LLM06 Sensitive Info       — `pii.guardMode` declares post-flight policy
 *   - LLM07 Insecure Plugin      — `tools[]` declares external integrations
 *   - LLM08 Excessive Agency     — `actionTier` declares approval boundary
 *   - LLM09 Overreliance         — `confidenceModel` declares verification
 *   - LLM10 Model Theft          — `outputClass` declares sensitivity
 *
 * The pre-existing `action-tiers.ts` covered LLM08 for 19 of 223 agents;
 * this manifest covers ALL 223 by static-analyzing each agent's source
 * code (db.insert/update/delete → tier ≥2; fetch() to external host →
 * tier 3 unless allowlisted; etc.).
 *
 * GENERATION
 * ──────────
 * Manifests are auto-generated by `scripts/analyze-agent-manifests.mjs`
 * which reads every src/app/api/_agents/<slug>/route.ts and derives
 * the fields below from imports + code patterns. The generator emits
 * `src/lib/agent-manifests.generated.ts` (committed alongside the
 * registry) which exports `AGENT_MANIFESTS: Record<slug, AgentManifest>`.
 *
 * Manual overrides — when static analysis under-classifies an agent
 * (e.g., it pretends to be Tier 1 but actually performs side effects
 * via a less obvious code path) — go in
 * `src/lib/agent-manifest-overrides.ts` and merge over the generated
 * data. Overrides record `reason` so the next reviewer understands.
 */

export type AgentTier = 1 | 2 | 3;

export const AGENT_TIER_LABEL: Record<AgentTier, string> = {
  1: "autonomous",
  2: "confirm",
  3: "admin-approval",
};

/**
 * Source-code signal classes the static analyzer extracts. Each signal
 * implies a tier floor; the agent's effective tier is `max(signals)`.
 */
export interface AgentSignal {
  kind:
    | "db_write"        // db.insert / db.update / db.delete
    | "db_read"         // db.select / db.query.X.findFirst
    | "external_fetch"  // fetch(url) to an off-platform host
    | "model_call"      // ai(), nimChat(), anthropic.messages.create
    | "email_send"      // resend.emails.send / sendEmail()
    | "voice_call"      // twilio voice / voice agents
    | "browser_control" // computer-use / playwright
    | "file_write"      // fs.writeFileSync / persist.ts
    | "payment_op"      // stripe / yoco
    | "uses_byok";      // BYOK key path (handles user secrets)
  detail?: string;
}

/**
 * What models the agent statically references. Helps auditors
 * verify provider claims match runtime behavior.
 */
export interface AgentModelRef {
  provider:
    | "nvidia-nim"
    | "anthropic"
    | "google"
    | "openai"
    | "groq"
    | "cerebras"
    | "ollama"
    | "xai"
    | "mistral"
    | "cohere"
    | "openrouter"
    | "together"
    | "databricks"
    | "replicate"
    | "unknown";
  inferenceFn: string; // e.g. "nimChat", "ai", "research_ai", "anthropic.messages.create"
}

/**
 * What external integrations / tools the agent statically calls.
 * Distinct from `models` — these are downstream business systems
 * (HubSpot, Slack, etc.) reachable via fetch() or imported clients.
 */
export interface AgentTool {
  name: string;
  origin: string; // best-effort hostname or library identifier
}

export interface AgentManifest {
  slug: string;

  /** OWASP LLM08 — agency boundary. Tier 1 = read-only / no side effects. */
  tier: AgentTier;
  tierReason: string;
  tierOverridden?: boolean;

  /** OWASP LLM05 — supply chain (per-agent SBOM). */
  models: AgentModelRef[];

  /** OWASP LLM07 — downstream tools / external integrations. */
  tools: AgentTool[];

  /** OWASP LLM06 — output PII policy. */
  pii: {
    guardMode: "mask" | "flag" | "skip" | "default-mask";
    handlesByDesign: boolean; // e.g. business-card-reader, resume-normalizer
  };

  /** OWASP LLM10 — output sensitivity classification. */
  outputClass: "public" | "tenant-private" | "confidential";

  /** All raw signals the static analyzer extracted (for transparency). */
  signals: AgentSignal[];

  /**
   * Confidence the static analyzer has in this classification (0..1).
   * Agents below 0.6 confidence are surfaced for manual review in
   * `scripts/analyze-agent-manifests.mjs --report`.
   */
  classifierConfidence: number;
}

/**
 * Pure function — given a set of signals, derive the action tier.
 *
 * Rules (in order of severity):
 *   - browser_control / payment_op / voice_call / email_send → Tier 3
 *     (external action, financial impact, or user-facing outbound)
 *   - db_write / file_write → Tier 2 (writes data; user should confirm)
 *   - external_fetch → Tier 2 (network egress to non-platform host)
 *   - everything else → Tier 1
 *
 * BYOK + PII handling do not affect tier on their own (they're
 * orthogonal capability axes that get their own audit columns).
 */
export function deriveTierFromSignals(
  signals: AgentSignal[],
): { tier: AgentTier; reason: string } {
  const kinds = new Set(signals.map((s) => s.kind));

  if (
    kinds.has("browser_control") ||
    kinds.has("payment_op") ||
    kinds.has("voice_call") ||
    kinds.has("email_send")
  ) {
    const why = [
      kinds.has("browser_control") ? "browser control" : null,
      kinds.has("payment_op") ? "payment operations" : null,
      kinds.has("voice_call") ? "voice calls" : null,
      kinds.has("email_send") ? "email send" : null,
    ]
      .filter(Boolean)
      .join(" + ");
    return { tier: 3, reason: `Tier 3: ${why} require admin approval` };
  }

  if (kinds.has("db_write") || kinds.has("file_write")) {
    return {
      tier: 2,
      reason: "Tier 2: writes data — user should confirm before execute",
    };
  }

  if (kinds.has("external_fetch")) {
    return {
      tier: 2,
      reason: "Tier 2: network egress to a non-platform host",
    };
  }

  return {
    tier: 1,
    reason: "Tier 1: read-only / inference-only / no side effects",
  };
}

/**
 * Pretty short label for an agent's effective tier — used in admin
 * dashboards and the public manifest endpoint.
 */
export function summarizeManifest(m: AgentManifest): string {
  const flags: string[] = [];
  if (m.pii.handlesByDesign) flags.push("PII");
  if (m.tools.length > 0) flags.push(`${m.tools.length} tools`);
  if (m.models.length > 0) flags.push(`${m.models.length} models`);
  return `${AGENT_TIER_LABEL[m.tier]}${flags.length ? ` · ${flags.join(", ")}` : ""}`;
}
