"use client";

import { motion } from "framer-motion";
import { ArrowRight, FileText, Share2, Shield, Brain, CheckCircle2, MessageSquare, Database, Layers, Zap } from "lucide-react";
import Link from "next/link";

const CAPABILITIES = [
  {
    icon: FileText,
    title: "SEO-first blog generation",
    desc: "Agents research keywords, analyze competitor content gaps, and write publish-ready posts. Each article is SEO-optimized with meta tags, internal links, and schema markup.",
    color: "cyan",
  },
  {
    icon: Share2,
    title: "Multi-channel distribution",
    desc: "One piece of content becomes 10. Blog post \u2192 LinkedIn post \u2192 Twitter thread \u2192 email newsletter \u2192 Instagram caption. Each adapted to platform conventions, not just reformatted.",
    color: "violet",
  },
  {
    icon: Shield,
    title: "Anti-slop quality engine",
    desc: "Every piece passes through the consensus engine. A Creator agent writes, a Critic agent reviews, a third model scores. AI detection rate stays below 5%. Reads like a human wrote it.",
    color: "emerald",
  },
  {
    icon: Brain,
    title: "Brand voice memory",
    desc: "Your tone, vocabulary, and style are stored in vector memory. Every future piece sounds like you \u2014 not like AI. The more you use it, the more accurate it gets.",
    color: "amber",
  },
];

const WORKFLOWS = [
  {
    trigger: "\"Write a blog post about AI agents replacing agency work\"",
    steps: [
      "Keyword research: 12 target keywords identified",
      "Competitive analysis: top 10 ranking articles analyzed",
      "First draft: 1,500 words generated by Content Agent",
      "Critique pass: Critic Agent identifies 4 improvements",
      "Final draft: revised, SEO scored 94/100, AI detection 3.8%",
    ],
    result: "Publish-ready article. 1,487 words. SEO score 94. AI detection 3.8%. Time: 2 minutes.",
  },
  {
    trigger: "\"Create a 5-email nurture sequence for new signups\"",
    steps: [
      "Pulls brand voice from memory",
      "Maps 5-stage journey (welcome, value, social proof, objection, CTA)",
      "Writes each email with personalization tokens",
      "A/B tests subject lines",
      "Quality scores all 5",
    ],
    result: "5 emails ready. Personalized per recipient. Average quality score: 91/100.",
  },
  {
    trigger: "\"Repurpose last week\u0027s blog into social content\"",
    steps: [
      "Reads blog from content library",
      "Extracts 8 key insights",
      "Generates LinkedIn post (professional tone)",
      "Generates Twitter thread (conversational)",
      "Generates Instagram caption (visual-first)",
      "Schedules all for optimal posting times",
    ],
    result: "8 social posts across 3 platforms. All brand-voiced. Scheduled for next 5 days.",
  },
];

export default function ContentEnginePage() {
  return (
    <div className="min-h-screen bg-[#010101] text-white">
      {/* Nav */}
      <nav className="px-6 md:px-10 h-16 flex items-center justify-between max-w-7xl mx-auto">
        <Link href="/" className="text-sm font-semibold text-white">Sovereign Matrix</Link>
        <Link href="/signup" className="px-5 py-2 rounded-full bg-white text-xs font-semibold text-black hover:bg-neutral-200 transition-colors">
          Get Started
        </Link>
      </nav>

      {/* Hero */}
      <section className="py-24 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-cyan-500/20 bg-cyan-500/[0.06] mb-6"
          >
            <FileText className="w-3.5 h-3.5 text-cyan-400" />
            <span className="text-[11px] font-semibold text-cyan-400 uppercase tracking-[0.2em]">Use Case</span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-4xl md:text-6xl font-black tracking-tight leading-[1.05] mb-6"
          >
            Your AI<br />
            <span className="text-cyan-400">content engine.</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="text-lg text-neutral-400 max-w-xl mx-auto leading-relaxed mb-8"
          >
            Blog posts, social media, email sequences, and landing pages &mdash; all generated,
            optimized, and published by autonomous agents. Human quality at machine speed.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="flex items-center justify-center gap-3"
          >
            <Link href="/signup" className="inline-flex items-center gap-2 px-8 py-4 bg-white text-black font-semibold rounded-full text-sm hover:bg-neutral-100 transition-all">
              Start your content engine <ArrowRight className="w-4 h-4" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* The pattern */}
      <section className="py-16 px-6 border-y border-white/[0.03]">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-[11px] font-medium uppercase tracking-[0.3em] text-cyan-500/60 mb-4">The Pattern</p>
            <h2 className="text-2xl md:text-4xl font-bold text-white tracking-tight mb-3">
              Create + Optimize + Publish
            </h2>
            <p className="text-sm text-neutral-500 max-w-lg mx-auto">
              Most AI writing tools give you a first draft. Sovereign gives you a publishing pipeline &mdash;
              from keyword research to multi-channel distribution.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            {CAPABILITIES.map((cap, i) => (
              <motion.div
                key={cap.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.08 }}
                className={`p-6 rounded-2xl border bg-[#080808] transition-all hover:border-${cap.color}-500/20 border-white/[0.05]`}
              >
                <div className={`w-10 h-10 rounded-xl bg-${cap.color}-500/10 flex items-center justify-center mb-4`}>
                  <cap.icon className={`w-5 h-5 text-${cap.color}-400`} />
                </div>
                <h3 className="text-base font-semibold text-white mb-2">{cap.title}</h3>
                <p className="text-sm text-neutral-400 leading-relaxed">{cap.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Workflow examples */}
      <section className="py-24 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <p className="text-[11px] font-medium uppercase tracking-[0.3em] text-cyan-500/60 mb-4">How It Works</p>
            <h2 className="text-2xl md:text-4xl font-bold text-white tracking-tight mb-3">
              Ask anything. Get content.
            </h2>
          </div>

          <div className="space-y-8">
            {WORKFLOWS.map((flow, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                className="rounded-2xl border border-white/[0.06] bg-[#080808] overflow-hidden"
              >
                {/* Trigger */}
                <div className="px-6 py-4 border-b border-white/[0.04] bg-[#060606]">
                  <div className="flex items-center gap-2 mb-1">
                    <MessageSquare className="w-3.5 h-3.5 text-cyan-400" />
                    <span className="text-[10px] text-cyan-500/60 uppercase tracking-wider font-semibold">You say</span>
                  </div>
                  <p className="text-sm text-white font-mono">{flow.trigger}</p>
                </div>

                {/* Steps */}
                <div className="px-6 py-4 space-y-2">
                  {flow.steps.map((step, j) => (
                    <div key={j} className="flex items-start gap-2.5 text-xs text-neutral-400">
                      <span className="text-cyan-500/50 font-mono shrink-0 mt-0.5">{String(j + 1).padStart(2, "0")}</span>
                      {step}
                    </div>
                  ))}
                </div>

                {/* Result */}
                <div className="px-6 py-4 border-t border-white/[0.04] bg-cyan-500/[0.02]">
                  <div className="flex items-start gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-cyan-400 shrink-0 mt-0.5" />
                    <p className="text-xs text-cyan-300">{flow.result}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Architecture */}
      <section className="py-16 px-6 border-y border-white/[0.03] bg-[#030303]">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-[11px] font-medium uppercase tracking-[0.3em] text-cyan-500/60 mb-4">Under The Hood</p>
            <h2 className="text-2xl md:text-3xl font-bold text-white tracking-tight">
              Built on real infrastructure.
            </h2>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { icon: Database, label: "Pinecone", desc: "Vector memory \u2014 semantic search across all your data" },
              { icon: Layers, label: "Neon Postgres", desc: "Tenant-scoped relational store \u2014 structured data" },
              { icon: Shield, label: "5-Layer Pipeline", desc: "Every retrieval passes through guardrails" },
              { icon: Zap, label: "Ollama Local", desc: "Air-gapped mode \u2014 nothing leaves your machine" },
            ].map((item) => (
              <div key={item.label} className="p-4 rounded-xl border border-white/[0.05] bg-white/[0.02]">
                <item.icon className="w-5 h-5 text-cyan-400 mb-3" />
                <div className="text-xs font-semibold text-white mb-0.5">{item.label}</div>
                <p className="text-[10px] text-neutral-500">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6 text-center">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-3xl md:text-5xl font-black text-white tracking-tight mb-4">
            Stop writing.<br />
            <span className="text-cyan-400">Start publishing.</span>
          </h2>
          <p className="text-neutral-400 mb-8 max-w-md mx-auto">
            Every piece of content is researched, written, critiqued, and optimized by autonomous agents.
            Your content engine gets better every day &mdash; without burnout.
          </p>
          <Link href="/signup" className="inline-flex items-center gap-2 px-8 py-4 bg-white text-black font-semibold rounded-full text-sm hover:bg-neutral-100 transition-all">
            Get started free <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>
    </div>
  );
}
