/**
 * /verified — public live demo of the Sovereign Verified badge.
 *
 * The "show, don't tell" page. Anyone can land here, see the badge
 * in action, copy the one-line embed snippet, and walk away with
 * a working integration plan in 60 seconds.
 *
 * Server-rendered for SEO. Pulls one recent public receipt to power
 * the live demo; falls back to a placeholder if none exist yet.
 */

import Link from "next/link";
import { headers } from "next/headers";
import {
  Shield,
  Code2,
  CheckCircle2,
  KeyRound,
  Eye,
  ArrowRight,
} from "lucide-react";
import Script from "next/script";
import { db } from "@/db";
import { agentRuns } from "@/db/schema";
import { desc, inArray } from "drizzle-orm";

export const dynamic = "force-dynamic";

async function getDemoReceiptId(): Promise<string | null> {
  try {
    const rows = await db
      .select({ id: agentRuns.id })
      .from(agentRuns)
      .where(inArray(agentRuns.visibility, ["public", "unlisted"]))
      .orderBy(desc(agentRuns.createdAt))
      .limit(1);
    return rows[0]?.id ?? null;
  } catch {
    return null;
  }
}

export default async function VerifiedPage() {
  const proto = (await headers()).get("x-forwarded-proto") ?? "https";
  const host =
    (await headers()).get("x-forwarded-host") ??
    (await headers()).get("host") ??
    "sovereignmatrix.agency";
  const origin = `${proto}://${host}`;

  const demoId = await getDemoReceiptId();

  const snippet = `<script src="${origin}/embed/verify.js"
        data-receipt="<your-receipt-id>"
        data-theme="dark"
        async></script>`;

  return (
    <div className="min-h-screen bg-[#030303] text-neutral-200">
      <div className="mx-auto max-w-4xl px-6 py-16">
        <Link
          href="/"
          className="mb-8 inline-flex items-center gap-2 text-sm text-neutral-500 transition hover:text-neutral-200"
        >
          ← Sovereign Matrix
        </Link>

        {/* Hero */}
        <header className="mb-12">
          <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-3 py-1 font-mono text-[11px] text-cyan-300">
            <Shield className="h-3 w-3" />
            VERIFIABLE AGENT INFRASTRUCTURE
          </div>
          <h1 className="font-serif text-5xl tracking-tight text-white md:text-7xl">
            One line of HTML.
            <br />
            <span style={{ color: "#22d3ee" }}>Cryptographic proof.</span>
          </h1>
          <p className="mt-5 max-w-2xl text-[17px] leading-relaxed text-neutral-400">
            Every agent run on Sovereign produces an HMAC-SHA256-signed receipt.
            Drop the embed badge on any page and your end users see a live
            verification — no log-in, no API key, no iframe.
          </p>
        </header>

        {/* Live demo */}
        <section className="mb-12 overflow-hidden rounded-2xl border border-white/[0.06] bg-white/[0.02] p-8 backdrop-blur-xl">
          <h2 className="mb-2 text-xs font-semibold uppercase tracking-wider text-neutral-400">
            Live demo
          </h2>
          <p className="mb-5 text-sm text-neutral-500">
            The badge below is the real script running against this deployment.
            Click it to open the underlying receipt.
          </p>

          <div className="rounded-xl border border-white/10 bg-black/40 p-8 text-center">
            {demoId ? (
              <>
                <p className="mb-4 text-xs font-mono uppercase tracking-wider text-neutral-600">
                  Generated by an actual Sovereign agent run:
                </p>
                <div className="flex items-center justify-center">
                  {/* eslint-disable-next-line @next/next/no-sync-scripts */}
                  <span data-sovereign-verify-host={demoId} />
                </div>
                <Script
                  src={`${origin}/embed/verify.js`}
                  data-receipt={demoId}
                  data-theme="dark"
                  strategy="afterInteractive"
                />
              </>
            ) : (
              <p className="text-sm text-neutral-500">
                Trigger any agent on the platform to generate the first public
                receipt. The badge will populate here automatically.
              </p>
            )}
          </div>

          <p className="mt-4 text-center text-[11px] text-neutral-600">
            View the underlying receipt at{" "}
            <code className="text-neutral-400">/r/&lt;id&gt;</code>. The badge
            fetches it cross-origin and verifies the HMAC signature via the
            public verifier.
          </p>
        </section>

        {/* Copy-paste snippet */}
        <section className="mb-12">
          <div className="mb-3 flex items-center gap-2">
            <Code2 className="h-4 w-4 text-cyan-300" />
            <h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-400">
              Drop one line on your site
            </h2>
          </div>
          <pre className="overflow-x-auto rounded-xl border border-white/10 bg-black/50 p-5 font-mono text-[13px] leading-relaxed text-cyan-200">
            {snippet}
          </pre>
          <p className="mt-3 text-xs text-neutral-500">
            Replace{" "}
            <code className="text-neutral-300">&lt;your-receipt-id&gt;</code>{" "}
            with the id from any agent run. Themes:{" "}
            <code className="text-neutral-300">dark</code> /{" "}
            <code className="text-neutral-300">light</code>. The badge auto-
            verifies on render and renders inline at the script tag&apos;s
            position. ~3.5 KB unminified, no external runtime.
          </p>
        </section>

        {/* What gets verified */}
        <section className="mb-12 grid grid-cols-1 gap-4 md:grid-cols-3">
          <Pillar
            Icon={KeyRound}
            title="HMAC-SHA256"
            body="Every receipt is signed server-side over a versioned canonical projection. The secret never leaves Sovereign's infrastructure."
          />
          <Pillar
            Icon={Eye}
            title="Cross-origin readable"
            body="Receipts marked public/unlisted are fetchable from any browser. Private receipts stay private — visibility gate enforced."
          />
          <Pillar
            Icon={CheckCircle2}
            title="Third-party verifiable"
            body="POST canonical+signature to /api/verify. Anyone can confirm authenticity without our help — including your auditor."
          />
        </section>

        {/* Why it matters */}
        <section className="mb-12 overflow-hidden rounded-2xl border border-white/[0.06] bg-gradient-to-br from-cyan-500/[0.04] to-transparent p-8 backdrop-blur-xl">
          <h2 className="mb-4 text-2xl font-semibold tracking-tight text-white">
            Why it matters
          </h2>
          <p className="mb-3 text-[15px] leading-relaxed text-neutral-300">
            Compliance teams have a real reason to block AI deployments: they
            can&apos;t prove what the model did, with which inputs, against what
            safety checks. Every audit conversation hits the same wall.
          </p>
          <p className="text-[15px] leading-relaxed text-neutral-400">
            A signed, replayable, third-party-verifiable receipt is the answer
            the wall is waiting for. POPIA Art. 22 requires explanation of
            automated decisions; SOC2 CC6 requires evidence of authorization.
            This badge is that evidence — embeddable, shareable, and impossible
            to forge.
          </p>
        </section>

        {/* Footer CTA */}
        <section className="text-center">
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 rounded-lg border border-cyan-500/30 bg-cyan-500/10 px-6 py-3 text-sm font-medium text-cyan-100 transition hover:border-cyan-400/50 hover:bg-cyan-500/15"
          >
            Get a free signing key
            <ArrowRight className="h-4 w-4" />
          </Link>
          <p className="mt-3 text-[11px] text-neutral-600">
            Free tier includes 50 verified runs / month. No credit card.
          </p>
        </section>
      </div>
    </div>
  );
}

function Pillar({
  Icon,
  title,
  body,
}: {
  Icon: typeof Shield;
  title: string;
  body: string;
}) {
  return (
    <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-5 backdrop-blur-xl">
      <Icon className="mb-3 h-5 w-5 text-cyan-300" />
      <h3 className="mb-2 text-sm font-semibold text-white">{title}</h3>
      <p className="text-xs leading-relaxed text-neutral-400">{body}</p>
    </div>
  );
}
