import type { Metadata } from "next";
import Link from "next/link";
import { buildIso42001, toMarkdown } from "@sovereign-matrix/iso-42001";
import type { ReceiptRecord } from "@sovereign-matrix/verifiable-receipts";
import { packageUrl } from "@/lib/package-links";

export const metadata: Metadata = {
  title: "ISO/IEC 42001 Report — Live Preview · Sovereign Matrix",
  description:
    "First-of-its-kind Apache 2.0 ISO/IEC 42001:2023 AIMS report exporter. Receipts in, regulator-ready report out. Live preview generated from a sample receipt set.",
};

// Sample receipts demonstrating the shape of an AIMS-grade audit window.
// Real operators feed their own production receipts; this is a marketing
// preview so visitors can SEE the output before installing the npm package.
const SAMPLE_RECEIPTS: ReceiptRecord[] = (() => {
  const base = new Date("2026-01-15T00:00:00Z").getTime();
  const day = 24 * 60 * 60 * 1000;
  const out: ReceiptRecord[] = [];
  const agents = [
    "loan-underwriter",
    "credit-analyst",
    "fraud-detector",
    "kyc-classifier",
  ];
  const packs = [
    "iso42001-aims",
    "iso42001-other",
    "gdpr-2026",
    "eu-ai-act-art-9",
    "owasp-agentic",
  ];
  for (let i = 0; i < 482; i++) {
    const verdictRoll = i % 47;
    const overall: ReceiptRecord["overall"] =
      verdictRoll < 41 ? "pass" : verdictRoll < 45 ? "warn" : "block";
    out.push({
      verdictId: `v_${i.toString(36).padStart(6, "0")}`,
      overall,
      issuedAt: new Date(base + i * 1000 * 60 * 15).toISOString(),
      agentSlug: agents[i % agents.length] as string,
      pack: packs[i % packs.length] as string,
      totalMs: 120 + ((i * 17) % 400),
      ...(i % 89 === 0 ? { anomalyKind: "block-rate-spike" } : {}),
    } as ReceiptRecord);
  }
  // Anchor the latest one ~today so the reporting window reads recent.
  out[out.length - 1]!.issuedAt = new Date(base + 120 * day).toISOString();
  return out;
})();

export default function Iso42001Preview() {
  const report = buildIso42001({
    scope: {
      organizationName: "Sample Operator — Acme AI Operations Ltd",
      scopeStatement:
        "All production AI agents serving consumer loan applicants in the EU.",
      aiSystemRole: "provider",
      certificationBody: "BSI",
      lastInternalAudit: "2026-03-15T00:00:00Z",
      nextManagementReview: "2026-09-15T00:00:00Z",
    },
    receipts: SAMPLE_RECEIPTS,
    retentionDays: 2555, // 7 years
    operatorActions: [
      "Tightened SR 11-7 model risk gate (2026-04-12).",
      "Added FAIR Act pack to underwriting flow (2026-04-21).",
      "Quarterly internal audit — closed 3 minor non-conformities (2026-04-30).",
    ],
  });

  const md = toMarkdown(report);
  const applicableControls = report.annexAControls.filter((c) => c.applicable);
  const withEvidence = applicableControls.filter((c) => c.evidenceCount > 0);

  return (
    <div className="relative min-h-dvh bg-[#030303] text-white antialiased">
      {/* Soft copper aurora — same brand language as / */}
      <div
        className="pointer-events-none absolute inset-x-0 top-0 h-[480px] opacity-30"
        aria-hidden="true"
        style={{
          background:
            "radial-gradient(ellipse 60% 70% at 50% 0%, rgba(181,83,44,0.18) 0%, transparent 70%)",
        }}
      />

      <main className="relative max-w-6xl mx-auto px-6 md:px-10 py-20 md:py-28">
        <div className="mb-12">
          <Link
            href="/"
            className="text-[12px] font-mono text-neutral-500 hover:text-neutral-300 transition-colors tracking-tight"
          >
            ← Sovereign Matrix
          </Link>
        </div>

        <div className="max-w-3xl">
          <p className="text-[10px] font-mono tracking-[0.22em] uppercase text-[#B5532C] mb-5">
            Live preview · Apache-2.0 OSS
          </p>
          <h1 className="font-serif text-5xl md:text-6xl leading-[1.04] tracking-[-0.02em] mb-6">
            ISO/IEC 42001:2023 report,
            <br />
            <em className="not-italic text-[#B5532C]">
              generated from receipts.
            </em>
          </h1>
          <p className="text-[17px] text-neutral-400 leading-[1.6] mb-3">
            This page is generated by{" "}
            <code className="font-mono text-[14px] text-cyan-300/90">
              @sovereign-matrix/iso-42001
            </code>{" "}
            from a sample receipt set. Feed your own production receipts in and
            you get the same shape — auditor-ready Markdown + GRC-tool JSON.
            Closed-source vendors charge $50-200K/yr for the same deliverable.
          </p>
          <p className="text-[14px] text-neutral-500 leading-relaxed">
            Below: structured summary + auditor-grade Markdown preview. Both are
            byte-deterministic from the receipt set — any external auditor with
            your receipts can reproduce these numbers exactly.
          </p>
        </div>

        {/* Install strip */}
        <div className="mt-12 rounded-[6px] border border-cyan-500/20 bg-black/40 overflow-hidden">
          <div className="px-5 py-3 border-b border-white/[0.05] flex items-center justify-between">
            <p className="text-[10px] font-mono uppercase tracking-widest text-neutral-500">
              Install · Apache 2.0
            </p>
            <p className="text-[10px] font-mono text-neutral-600">
              Zero runtime deps beyond verifiable-receipts
            </p>
          </div>
          <pre className="px-5 py-4 overflow-x-auto font-mono text-[13px] leading-[1.6] text-cyan-300/95">
            {`npm install @sovereign-matrix/iso-42001 @sovereign-matrix/verifiable-receipts`}
          </pre>
        </div>

        {/* Sample scope */}
        <section className="mt-16">
          <h2 className="font-serif text-3xl md:text-4xl mb-6 tracking-tight">
            Scope
          </h2>
          <div className="grid md:grid-cols-2 gap-4 text-[14px]">
            <KV k="Organization" v={report.scope.organizationName} />
            <KV k="AI system role" v={report.scope.aiSystemRole} />
            <KV k="Scope statement" v={report.scope.scopeStatement} wide />
            {report.scope.certificationBody && (
              <KV k="Certification body" v={report.scope.certificationBody} />
            )}
            <KV
              k="Reporting window"
              v={`${report.reportingWindow.from.slice(0, 10)} → ${report.reportingWindow.to.slice(0, 10)}`}
            />
            <KV
              k="Total receipts"
              v={report.reportingWindow.totalReceipts.toLocaleString()}
            />
          </div>
        </section>

        {/* Derived clauses summary */}
        <section className="mt-16">
          <h2 className="font-serif text-3xl md:text-4xl mb-6 tracking-tight">
            Derived from receipts
          </h2>
          <p className="text-[13px] text-neutral-500 mb-6 max-w-2xl">
            Clauses 7-10 + Annex A control evidence are computed directly from
            the receipt set. Each row carries a{" "}
            <span className="text-[#B5532C]">derived: true</span> flag so
            auditors can distinguish operator narrative from cryptographic
            evidence.
          </p>
          <div className="grid md:grid-cols-2 gap-4">
            <ClauseCard
              n="7"
              title="Support (§ 7.5 documented information)"
              rows={[
                [
                  "Documented information",
                  report.clause7Support.documentedInformationCount.toString(),
                ],
                [
                  "Retention window",
                  `${report.clause7Support.retentionWindowDays} days`,
                ],
                ["Integrity mechanism", "Ed25519 + ML-DSA-65"],
              ]}
            />
            <ClauseCard
              n="8"
              title="Operation"
              rows={[
                ["Pass", report.clause8Operation.verdictCounts.pass.toString()],
                ["Warn", report.clause8Operation.verdictCounts.warn.toString()],
                [
                  "Block",
                  report.clause8Operation.verdictCounts.block.toString(),
                ],
                [
                  "Block-rate",
                  `${(report.clause8Operation.blockRate * 100).toFixed(2)}%`,
                ],
                [
                  "Agents operated",
                  report.clause8Operation.agentsOperated.length.toString(),
                ],
                [
                  "Guardian packs applied",
                  report.clause8Operation.packsApplied.length.toString(),
                ],
              ]}
            />
            <ClauseCard
              n="9"
              title="Performance evaluation"
              rows={[
                [
                  "p50 latency",
                  `${report.clause9Performance.p50LatencyMs ?? "n/a"} ms`,
                ],
                [
                  "p99 latency",
                  `${report.clause9Performance.p99LatencyMs ?? "n/a"} ms`,
                ],
                [
                  "Receipts/day",
                  report.clause9Performance.receiptsPerDay.toFixed(1),
                ],
                [
                  "Anomalies detected",
                  report.clause9Performance.anomaliesDetected.toString(),
                ],
              ]}
            />
            <ClauseCard
              n="10"
              title="Improvement"
              rows={[
                [
                  "Operator actions",
                  report.clause10Improvement.operatorActions.length.toString(),
                ],
                [
                  "Distinct agents",
                  report.clause10Improvement.distinctAgentsOverWindow.toString(),
                ],
                [
                  "Distinct packs",
                  report.clause10Improvement.distinctPacksOverWindow.toString(),
                ],
              ]}
            />
          </div>
        </section>

        {/* Annex A coverage */}
        <section className="mt-16">
          <h2 className="font-serif text-3xl md:text-4xl mb-2 tracking-tight">
            Annex A control coverage
          </h2>
          <p className="text-[13px] text-neutral-500 mb-6 max-w-2xl">
            38 reference controls (A.2.2 — A.10.4) with receipt-derived evidence
            counts. Operators can override applicability per their § 6.1.3
            statement of applicability.
          </p>

          <div className="flex flex-wrap gap-4 mb-6 text-[12px] font-mono">
            <Stat
              label="Applicable"
              value={applicableControls.length}
              total={38}
            />
            <Stat
              label="With evidence"
              value={withEvidence.length}
              total={applicableControls.length}
              accent
            />
            <Stat
              label="Without evidence"
              value={applicableControls.length - withEvidence.length}
              total={applicableControls.length}
              warn
            />
          </div>

          <div className="rounded-[6px] border border-white/[0.06] overflow-hidden">
            <table className="w-full text-[12px]">
              <thead className="bg-white/[0.02] text-neutral-500 font-mono uppercase tracking-[0.14em] text-[10px]">
                <tr>
                  <th className="text-left px-4 py-2.5">Control</th>
                  <th className="text-left px-4 py-2.5">Title</th>
                  <th className="text-right px-4 py-2.5">Evidence</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/[0.04]">
                {report.annexAControls.map((c) => (
                  <tr
                    key={c.id}
                    className="hover:bg-white/[0.02] transition-colors"
                  >
                    <td className="px-4 py-2 font-mono text-cyan-300/90 text-[11px]">
                      {c.id}
                    </td>
                    <td className="px-4 py-2 text-neutral-300">{c.title}</td>
                    <td className="px-4 py-2 text-right font-mono">
                      {c.evidenceCount > 0 ? (
                        <span className="text-emerald-400">
                          {c.evidenceCount}
                        </span>
                      ) : (
                        <span className="text-neutral-600">0</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Markdown preview */}
        <section className="mt-16">
          <h2 className="font-serif text-3xl md:text-4xl mb-2 tracking-tight">
            Markdown preview
          </h2>
          <p className="text-[13px] text-neutral-500 mb-6 max-w-2xl">
            The exact bytes{" "}
            <code className="text-cyan-300/90">toMarkdown(report)</code>{" "}
            returned. File this with your auditor; ingest the JSON into your GRC
            tool.
          </p>
          <div className="rounded-[6px] border border-white/[0.06] bg-black/40 max-h-[560px] overflow-y-auto">
            <pre className="px-5 py-4 font-mono text-[11px] leading-[1.55] text-neutral-300 whitespace-pre-wrap break-words">
              {md.slice(0, 4500)}
              {md.length > 4500 &&
                "\n\n… (truncated — full output is ~" +
                  (md.length / 1000).toFixed(1) +
                  "kB)"}
            </pre>
          </div>
        </section>

        {/* CTA */}
        <section className="mt-20 mb-8 rounded-[10px] border border-[#B5532C]/20 bg-[#1a0f0a]/40 px-6 md:px-10 py-10 md:py-14">
          <p className="text-[10px] font-mono uppercase tracking-[0.22em] text-[#B5532C] mb-4">
            Ship audit-ready
          </p>
          <h3 className="font-serif text-3xl md:text-4xl mb-4 tracking-tight">
            Three lines around your AI calls.
            <br />
            <em className="not-italic text-[#B5532C]">
              A regulator-ready report every quarter.
            </em>
          </h3>
          <p className="text-[14px] text-neutral-400 leading-relaxed mb-6 max-w-2xl">
            Sovereign Matrix runs the receipt pipeline and produces these
            reports automatically. Free tier: 50 verified runs / month. Growth
            from R4,997/mo (~$49). No per-seat fees.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link
              href="/sign-up"
              className="inline-flex items-center gap-2 px-5 py-3 bg-[#B5532C] text-white font-semibold text-[13px] rounded-[3px] hover:bg-[#C96234] transition-colors tracking-tight"
            >
              Start free — 50 runs/mo
              <span aria-hidden="true">→</span>
            </Link>
            <Link
              href={packageUrl("@sovereign-matrix/iso-42001")}
              className="inline-flex items-center gap-2 px-5 py-3 border border-white/[0.12] text-neutral-300 font-mono text-[13px] rounded-[3px] hover:text-white hover:border-white/25 transition-colors"
            >
              View source
            </Link>
            <Link
              href="/pricing"
              className="inline-flex items-center gap-2 px-5 py-3 text-neutral-500 hover:text-white font-mono text-[13px] transition-colors"
            >
              Pricing →
            </Link>
          </div>
        </section>

        <footer className="mt-16 pt-8 border-t border-white/[0.04] text-[12px] font-mono text-neutral-600">
          Generated by{" "}
          <code className="text-cyan-300/80">@sovereign-matrix/iso-42001</code>{" "}
          v0.1.0 · Apache 2.0 · schema{" "}
          <code className="text-cyan-300/80">vaos-iso-42001-v1</code>
        </footer>
      </main>
    </div>
  );
}

function KV({ k, v, wide }: { k: string; v: string; wide?: boolean }) {
  return (
    <div
      className={`rounded-[6px] border border-white/[0.06] bg-white/[0.015] px-4 py-3 ${wide ? "md:col-span-2" : ""}`}
    >
      <p className="font-mono text-[10px] uppercase tracking-[0.14em] text-neutral-500 mb-1">
        {k}
      </p>
      <p className="text-neutral-200 text-[14px]">{v}</p>
    </div>
  );
}

function ClauseCard({
  n,
  title,
  rows,
}: {
  n: string;
  title: string;
  rows: [string, string][];
}) {
  return (
    <div className="rounded-[6px] border border-white/[0.06] bg-white/[0.015] p-5">
      <div className="flex items-baseline gap-3 mb-4">
        <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#B5532C]">
          § {n}
        </span>
        <h3 className="font-serif text-[18px] tracking-tight">{title}</h3>
      </div>
      <ul className="space-y-1.5 text-[13px]">
        {rows.map(([k, v]) => (
          <li key={k} className="flex items-baseline justify-between gap-3">
            <span className="text-neutral-500">{k}</span>
            <span className="font-mono text-neutral-200">{v}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function Stat({
  label,
  value,
  total,
  accent,
  warn,
}: {
  label: string;
  value: number;
  total: number;
  accent?: boolean;
  warn?: boolean;
}) {
  const color = accent
    ? "text-emerald-400"
    : warn
      ? "text-amber-400"
      : "text-neutral-300";
  return (
    <span className="inline-flex items-baseline gap-1.5 rounded-[3px] border border-white/[0.06] bg-white/[0.02] px-3 py-1.5">
      <span className="text-[10px] uppercase tracking-[0.14em] text-neutral-500">
        {label}
      </span>
      <span className={`text-[14px] font-semibold ${color}`}>{value}</span>
      <span className="text-neutral-600">/ {total}</span>
    </span>
  );
}
