/**
 * SOVEREIGN MATRIX — Model Registry
 *
 * Centralized model configuration used by the chat UI, smart router,
 * and model switcher. Single source of truth for all available models.
 */

export interface ModelConfig {
  id: string;
  name: string;
  provider: "nvidia" | "google" | "anthropic" | "groq" | "meta" | "deepseek" | "alibaba" | "zhipu" | "local";
  description: string;
  tags: ModelTag[];
  contextWindow: number;
  speedTier: "instant" | "fast" | "standard" | "slow";
  costTier: "free" | "byok" | "metered";
  color: string; // provider accent color
}

export type ModelTag = "reasoning" | "code" | "vision" | "thinking" | "fast" | "streaming" | "agentic" | "long-context" | "free" | "tools" | "voice" | "multilingual" | "creative" | "speech" | "video";

export const PROVIDER_COLORS: Record<ModelConfig["provider"], string> = {
  nvidia: "#76B900",
  google: "#4285F4",
  anthropic: "#D4A574",
  groq: "#F55036",
  meta: "#0668E1",
  deepseek: "#4D6BFE",
  alibaba: "#FF6A00",
  zhipu: "#4A90D9",
  local: "#10B981",
};

export const PROVIDER_LABELS: Record<ModelConfig["provider"], string> = {
  nvidia: "NVIDIA NIM",
  google: "Google",
  anthropic: "Anthropic",
  groq: "Groq",
  meta: "Meta",
  deepseek: "DeepSeek",
  alibaba: "Alibaba",
  zhipu: "Zhipu AI",
  local: "Local",
};

export const MODEL_REGISTRY: ModelConfig[] = [
  {
    id: "auto",
    name: "Auto",
    provider: "nvidia",
    description: "Smart routing picks the best model for your task",
    tags: ["reasoning", "code", "fast"],
    contextWindow: 128000,
    speedTier: "fast",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "nemotron",
    name: "Nemotron Ultra",
    provider: "nvidia",
    description: "253B — synthesis, debate, deep reasoning",
    tags: ["reasoning", "agentic", "free"],
    contextWindow: 32768,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "qwen3",
    name: "Qwen 3",
    provider: "alibaba",
    description: "235B MoE — dual thinking/fast mode",
    tags: ["thinking", "code", "multilingual", "free"],
    contextWindow: 131072,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.alibaba,
  },
  {
    id: "deepseek",
    name: "DeepSeek V3.2",
    provider: "deepseek",
    description: "Best open-source for reasoning + agentic workloads",
    tags: ["reasoning", "code", "agentic", "free"],
    contextWindow: 131072,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.deepseek,
  },
  {
    id: "llama4",
    name: "Llama 4 Maverick",
    provider: "meta",
    description: "17B multimodal — images + text",
    tags: ["vision", "creative", "free"],
    contextWindow: 128000,
    speedTier: "fast",
    costTier: "free",
    color: PROVIDER_COLORS.meta,
  },
  {
    id: "glm5",
    name: "GLM-5",
    provider: "zhipu",
    description: "400B — long-horizon agentic tasks",
    tags: ["agentic", "reasoning", "free"],
    contextWindow: 128000,
    speedTier: "slow",
    costTier: "free",
    color: PROVIDER_COLORS.zhipu,
  },
  {
    id: "nemotron3",
    name: "Nemotron 3 Super",
    provider: "nvidia",
    description: "120B — 1M context, hybrid architecture",
    tags: ["long-context", "reasoning", "free"],
    contextWindow: 1048576,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "devstral",
    name: "Devstral 2",
    provider: "nvidia",
    description: "123B — code specialist, HTML/CSS/JS",
    tags: ["code", "free"],
    contextWindow: 131072,
    speedTier: "fast",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "claude",
    name: "Claude",
    provider: "anthropic",
    description: "Sonnet — reasoning, tools, structured output",
    tags: ["reasoning", "tools", "code"],
    contextWindow: 200000,
    speedTier: "fast",
    costTier: "byok",
    color: PROVIDER_COLORS.anthropic,
  },
  {
    id: "gemini",
    name: "Gemini 2.5",
    provider: "google",
    description: "Flash — fast streaming, multimodal",
    tags: ["fast", "streaming", "vision"],
    contextWindow: 1048576,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.google,
  },
  // ─── Frontier Models (Wave 3) ───
  {
    id: "kimi-dev-72b",
    name: "Kimi-Dev-72B",
    provider: "local",
    description: "72B — SOTA SWE-bench, best open-source code model",
    tags: ["code", "free"],
    contextWindow: 131072,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.local,
  },
  {
    id: "llama4-scout",
    name: "Llama 4 Scout",
    provider: "meta",
    description: "17B — 10M context window, natively multimodal",
    tags: ["long-context", "vision", "free"],
    contextWindow: 10485760,
    speedTier: "fast",
    costTier: "free",
    color: PROVIDER_COLORS.meta,
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek-R1 Full",
    provider: "deepseek",
    description: "97.3% MATH-500 — frontier reasoning model",
    tags: ["reasoning", "thinking", "free"],
    contextWindow: 131072,
    speedTier: "slow",
    costTier: "free",
    color: PROVIDER_COLORS.deepseek,
  },
  {
    id: "phi-4",
    name: "Phi-4",
    provider: "local",
    description: "14B — rivals larger models, great for edge/local",
    tags: ["fast", "free"],
    contextWindow: 16384,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.local,
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "local",
    description: "1T params — vision, code, reasoning, math",
    tags: ["vision", "code", "reasoning", "free"] as ModelTag[],
    contextWindow: 262144,
    speedTier: "standard" as const,
    costTier: "free" as const,
    color: PROVIDER_COLORS.local,
  },
  // ─── GTC 2026 — NemoClaw RTX AI Garage Models ───
  {
    id: "nemotron-nano-4b",
    name: "Nemotron 3 Nano",
    provider: "nvidia",
    description: "4B — ultra-lightweight, runs on any GeForce RTX",
    tags: ["fast", "free", "agentic"],
    contextWindow: 8192,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "mistral-small-4",
    name: "Mistral Small 4",
    provider: "nvidia",
    description: "119B (6B active) — unified chat + code + agents",
    tags: ["code", "agentic", "fast", "free"],
    contextWindow: 131072,
    speedTier: "fast",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "qwen3.5-27b",
    name: "Qwen 3.5 27B",
    provider: "alibaba",
    description: "27B — vision + multi-token prediction, 262K context",
    tags: ["vision", "multilingual", "long-context", "free"],
    contextWindow: 262144,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.alibaba,
  },
  // ─── March 2026 Wave 4 — Latest Releases ───
  {
    id: "qwen3.5-small",
    name: "Qwen 3.5 Small",
    provider: "alibaba",
    description: "9B multimodal (text+image+video) — runs on any Mac",
    tags: ["vision", "fast", "multilingual", "free"],
    contextWindow: 131072,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.alibaba,
  },
  {
    id: "nemotron-speech",
    name: "Nemotron Speech",
    provider: "nvidia",
    description: "Real-time low-latency speech recognition",
    tags: ["speech", "voice", "fast", "free"],
    contextWindow: 16384,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "ltx-2.3",
    name: "LTX 2.3",
    provider: "local",
    description: "22B — 4K video generation with synchronized audio",
    tags: ["video", "creative", "free"],
    contextWindow: 8192,
    speedTier: "slow",
    costTier: "free",
    color: PROVIDER_COLORS.local,
  },
  {
    id: "helios",
    name: "Helios",
    provider: "local",
    description: "60-second video at real-time speed on 1 GPU",
    tags: ["video", "creative", "fast", "free"],
    contextWindow: 8192,
    speedTier: "fast",
    costTier: "free",
    color: PROVIDER_COLORS.local,
  },
  // ─── April 2026 Wave 5 — Latest Frontier Models ───
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    provider: "google",
    description: "Leads 13/16 benchmarks, 1/3 the cost of GPT-5.4 Pro",
    tags: ["reasoning", "code", "vision", "long-context"],
    contextWindow: 2097152,
    speedTier: "fast",
    costTier: "free",
    color: PROVIDER_COLORS.google,
  },
  {
    id: "nemotron-cascade-2",
    name: "Nemotron Cascade 2",
    provider: "nvidia",
    description: "Hybrid Mamba-Transformer MoE — 1M context, agentic reasoning",
    tags: ["reasoning", "agentic", "long-context", "free"],
    contextWindow: 1048576,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "llama4-maverick",
    name: "Llama 4 Maverick",
    provider: "meta",
    description: "400B — 10M context, strongest open-weight model",
    tags: ["reasoning", "vision", "long-context", "free"],
    contextWindow: 10485760,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.meta,
  },
  // ─── Wave 6 — Additional NIM + Provider Models ───
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    description: "Ultra-fast streaming, 1M context, multimodal",
    tags: ["fast", "streaming", "vision", "long-context"],
    contextWindow: 1048576,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.google,
  },
  {
    id: "groq-llama3",
    name: "Llama 3 via Groq",
    provider: "groq",
    description: "Ultra-low latency (<100ms) via Groq LPU chips",
    tags: ["fast", "reasoning", "free"],
    contextWindow: 131072,
    speedTier: "instant",
    costTier: "free",
    color: "#F55036",
  },
  {
    id: "groq-mixtral",
    name: "Mixtral via Groq",
    provider: "groq",
    description: "MoE model, ultra-fast inference on Groq hardware",
    tags: ["fast", "multilingual", "free"],
    contextWindow: 32768,
    speedTier: "instant",
    costTier: "free",
    color: "#F55036",
  },
  {
    id: "cerebras-llama3",
    name: "Llama 3 via Cerebras",
    provider: "local",
    description: "2,200+ tok/s on Cerebras wafer-scale engine",
    tags: ["fast", "reasoning", "free"],
    contextWindow: 131072,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.local,
  },
  {
    id: "claude-opus",
    name: "Claude Opus 4.6",
    provider: "anthropic",
    description: "Most capable Claude — deep reasoning, 200K context",
    tags: ["reasoning", "code", "agentic"],
    contextWindow: 200000,
    speedTier: "standard",
    costTier: "metered",
    color: PROVIDER_COLORS.anthropic,
  },
  {
    id: "flux1-pro",
    name: "FLUX.1 Pro",
    provider: "nvidia",
    description: "High-quality image generation via Black Forest Labs",
    tags: ["creative", "free"],
    contextWindow: 0,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "llama-guard-3",
    name: "LlamaGuard 3",
    provider: "nvidia",
    description: "Dedicated safety classification model for content moderation",
    tags: ["free"],
    contextWindow: 8192,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "magpie-tts",
    name: "NVIDIA Magpie TTS",
    provider: "nvidia",
    description: "Text-to-speech voice synthesis, natural sounding",
    tags: ["voice", "speech", "free"],
    contextWindow: 0,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "nemo-guardrails",
    name: "NeMo Guardrails",
    provider: "nvidia",
    description: "5-layer safety pipeline for agent output verification",
    tags: ["free"],
    contextWindow: 0,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "rerank-v2",
    name: "NIM Reranker v2",
    provider: "nvidia",
    description: "Search result reranking for RAG accuracy improvement",
    tags: ["free"],
    contextWindow: 8192,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "embed-v2",
    name: "NIM Embeddings v2",
    provider: "nvidia",
    description: "Text embeddings for vector search and memory",
    tags: ["free"],
    contextWindow: 8192,
    speedTier: "instant",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  {
    id: "gemma-4",
    name: "Gemma 4",
    provider: "google",
    description: "31B — 256K context, vision+audio, 140 languages",
    tags: ["vision", "multilingual", "free"],
    contextWindow: 262144,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.google,
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    provider: "nvidia",
    description: "123B — strong reasoning, multilingual, code",
    tags: ["reasoning", "code", "multilingual", "free"],
    contextWindow: 131072,
    speedTier: "standard",
    costTier: "free",
    color: PROVIDER_COLORS.nvidia,
  },
  // ─── Project Glasswing — Claude Mythos Preview (coming soon) ───
  // See: anthropic.com/glasswing
  // Mythos Preview won't be GA — capabilities will ship in a future Opus model.
  // SWE-bench Pro: 77.8% (vs Opus 4.6 53.4%), CyberGym: 83.1% (vs 66.6%)
  // Found 0-days in OpenBSD (27-year flaw), FFmpeg (16-year flaw), Linux kernel privesc
  // Pricing: $25/$125 per M input/output tokens
  {
    id: "claude-mythos",
    name: "Claude Mythos",
    provider: "anthropic",
    description: "Frontier — autonomous vulnerability detection, 77.8% SWE-bench Pro",
    tags: ["code", "reasoning", "agentic"],
    contextWindow: 200000,
    speedTier: "standard",
    costTier: "metered",
    color: PROVIDER_COLORS.anthropic,
  },
];

export function getModel(id: string): ModelConfig {
  return MODEL_REGISTRY.find(m => m.id === id) || MODEL_REGISTRY[0];
}

export function getModelsByTag(tag: ModelTag): ModelConfig[] {
  return MODEL_REGISTRY.filter(m => m.tags.includes(tag));
}

export function getFreeModels(): ModelConfig[] {
  return MODEL_REGISTRY.filter(m => m.costTier === "free");
}
