/**
 * HIPAA Security Rule — 45 CFR §§ 164.308–164.316.
 *
 * Every implementation specification carries its required /
 * addressable classification, which changes what a gap means: a
 * missing required specification is a finding, a missing addressable
 * one needs a documented rationale.
 *
 * 52 specifications. Data only — the engine renders it.
 *
 * @packageDocumentation
 */

import type { RegulationPack } from "../types.js";

export const HIPAA_SECURITY_PACK: RegulationPack = {
  id: "hipaa-security",
  standard: "HIPAA Security Rule (45 CFR Part 164, Subpart C)",
  reportTitle: "HIPAA Security Rule Evidence Binder",
  schema: "vaos-hipaa-security-v1",
  preamble:
    "This binder maps each implementation specification of the HIPAA Security Rule (45 CFR Part 164 Subpart C) to receipt-derived evidence. Required specifications must be implemented; addressable specifications must be implemented, or an equivalent alternative documented. A gap against an addressable specification is not automatically a violation — it is a place the operator owes a written rationale.",
  controlNoun: { singular: "specification", plural: "specifications" },
  categories: [
    "administrative",
    "physical",
    "technical",
    "organizational",
    "policies",
  ],
  metaColumns: [
    { key: "classification", header: "R/A" },
    { key: "standard", header: "Standard" },
  ],
  controls: [
    // ── administrative ──────────────────────────────────────────────
    {
      id: "164.308(a)(1)(i)",
      category: "administrative",
      title: "Security Management Process — Standard",
      objective: "Implement policies and procedures to prevent, detect, contain, and correct security violations.",
      evidencePackPrefixes: ["hipaa", "soc2-cc1"],
      meta: { standard: "164.308(a)(1) Security Management Process", classification: "required" },
    },
    {
      id: "164.308(a)(1)(ii)(A)",
      category: "administrative",
      title: "Risk Analysis",
      objective: "Conduct an accurate and thorough assessment of the potential risks and vulnerabilities to the confidentiality, integrity, and availability of ePHI.",
      evidencePackPrefixes: ["hipaa", "risk-assessment", "owasp"],
      meta: { standard: "164.308(a)(1) Security Management Process", classification: "required" },
    },
    {
      id: "164.308(a)(1)(ii)(B)",
      category: "administrative",
      title: "Risk Management",
      objective: "Implement security measures sufficient to reduce risks and vulnerabilities to a reasonable and appropriate level.",
      evidencePackPrefixes: ["hipaa"],
      meta: { standard: "164.308(a)(1) Security Management Process", classification: "required" },
    },
    {
      id: "164.308(a)(1)(ii)(C)",
      category: "administrative",
      title: "Sanction Policy",
      objective: "Apply appropriate sanctions against workforce members who fail to comply with the security policies and procedures.",
      evidencePackPrefixes: ["hipaa", "policy"],
      meta: { standard: "164.308(a)(1) Security Management Process", classification: "required" },
    },
    {
      id: "164.308(a)(1)(ii)(D)",
      category: "administrative",
      title: "Information System Activity Review",
      objective: "Implement procedures to regularly review records of information system activity (audit logs, access reports, security incident tracking).",
      evidencePackPrefixes: ["hipaa", "audit-log", "anomaly"],
      meta: { standard: "164.308(a)(1) Security Management Process", classification: "required" },
    },
    {
      id: "164.308(a)(2)",
      category: "administrative",
      title: "Assigned Security Responsibility",
      objective: "Identify the security official who is responsible for the development and implementation of the policies and procedures.",
      evidencePackPrefixes: ["hipaa"],
      meta: { standard: "164.308(a)(2) Assigned Security Responsibility", classification: "required" },
    },
    {
      id: "164.308(a)(3)(i)",
      category: "administrative",
      title: "Workforce Security — Standard",
      objective: "Ensure all members of the workforce have appropriate access to ePHI and prevent unauthorized access.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.308(a)(3) Workforce Security", classification: "required" },
    },
    {
      id: "164.308(a)(3)(ii)(A)",
      category: "administrative",
      title: "Authorization and/or Supervision",
      objective: "Implement procedures for the authorization and/or supervision of workforce members who work with ePHI.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.308(a)(3) Workforce Security", classification: "addressable" },
    },
    {
      id: "164.308(a)(3)(ii)(B)",
      category: "administrative",
      title: "Workforce Clearance Procedure",
      objective: "Implement procedures to determine that the access of a workforce member to ePHI is appropriate.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.308(a)(3) Workforce Security", classification: "addressable" },
    },
    {
      id: "164.308(a)(3)(ii)(C)",
      category: "administrative",
      title: "Termination Procedures",
      objective: "Implement procedures for terminating access to ePHI when a workforce member's employment ends.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.308(a)(3) Workforce Security", classification: "addressable" },
    },
    {
      id: "164.308(a)(4)(i)",
      category: "administrative",
      title: "Information Access Management — Standard",
      objective: "Implement policies and procedures for authorizing access to ePHI.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.308(a)(4) Information Access Management", classification: "required" },
    },
    {
      id: "164.308(a)(4)(ii)(B)",
      category: "administrative",
      title: "Access Authorization",
      objective: "Implement policies and procedures for granting access to ePHI through access to a workstation, transaction, program, process, or other mechanism.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.308(a)(4) Information Access Management", classification: "addressable" },
    },
    {
      id: "164.308(a)(4)(ii)(C)",
      category: "administrative",
      title: "Access Establishment and Modification",
      objective: "Implement policies and procedures that establish, document, review, and modify a user's right of access.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.308(a)(4) Information Access Management", classification: "addressable" },
    },
    {
      id: "164.308(a)(5)(i)",
      category: "administrative",
      title: "Security Awareness and Training — Standard",
      objective: "Implement a security awareness and training program for all members of the workforce.",
      evidencePackPrefixes: ["hipaa", "training"],
      meta: { standard: "164.308(a)(5) Security Awareness and Training", classification: "required" },
    },
    {
      id: "164.308(a)(5)(ii)(A)",
      category: "administrative",
      title: "Security Reminders",
      objective: "Periodic security updates.",
      evidencePackPrefixes: ["hipaa", "training"],
      meta: { standard: "164.308(a)(5) Security Awareness and Training", classification: "addressable" },
    },
    {
      id: "164.308(a)(5)(ii)(B)",
      category: "administrative",
      title: "Protection from Malicious Software",
      objective: "Procedures for guarding against, detecting, and reporting malicious software.",
      evidencePackPrefixes: ["hipaa", "antivirus", "supply-chain"],
      meta: { standard: "164.308(a)(5) Security Awareness and Training", classification: "addressable" },
    },
    {
      id: "164.308(a)(5)(ii)(C)",
      category: "administrative",
      title: "Log-in Monitoring",
      objective: "Procedures for monitoring log-in attempts and reporting discrepancies.",
      evidencePackPrefixes: ["hipaa", "auth", "anomaly"],
      meta: { standard: "164.308(a)(5) Security Awareness and Training", classification: "addressable" },
    },
    {
      id: "164.308(a)(5)(ii)(D)",
      category: "administrative",
      title: "Password Management",
      objective: "Procedures for creating, changing, and safeguarding passwords.",
      evidencePackPrefixes: ["hipaa", "auth"],
      meta: { standard: "164.308(a)(5) Security Awareness and Training", classification: "addressable" },
    },
    {
      id: "164.308(a)(6)(i)",
      category: "administrative",
      title: "Security Incident Procedures — Standard",
      objective: "Implement policies and procedures to address security incidents.",
      evidencePackPrefixes: ["hipaa", "incident-response"],
      meta: { standard: "164.308(a)(6) Security Incident Procedures", classification: "required" },
    },
    {
      id: "164.308(a)(6)(ii)",
      category: "administrative",
      title: "Response and Reporting",
      objective: "Identify and respond to suspected or known security incidents; mitigate, to the extent practicable, harmful effects.",
      evidencePackPrefixes: ["hipaa", "incident-response"],
      meta: { standard: "164.308(a)(6) Security Incident Procedures", classification: "required" },
    },
    {
      id: "164.308(a)(7)(i)",
      category: "administrative",
      title: "Contingency Plan — Standard",
      objective: "Establish policies and procedures for responding to an emergency or other occurrence that damages systems containing ePHI.",
      evidencePackPrefixes: ["hipaa", "dr", "bcp"],
      meta: { standard: "164.308(a)(7) Contingency Plan", classification: "required" },
    },
    {
      id: "164.308(a)(7)(ii)(A)",
      category: "administrative",
      title: "Data Backup Plan",
      objective: "Establish procedures to create and maintain retrievable exact copies of ePHI.",
      evidencePackPrefixes: ["hipaa", "backup"],
      meta: { standard: "164.308(a)(7) Contingency Plan", classification: "required" },
    },
    {
      id: "164.308(a)(7)(ii)(B)",
      category: "administrative",
      title: "Disaster Recovery Plan",
      objective: "Establish procedures to restore any loss of data.",
      evidencePackPrefixes: ["hipaa", "dr"],
      meta: { standard: "164.308(a)(7) Contingency Plan", classification: "required" },
    },
    {
      id: "164.308(a)(7)(ii)(C)",
      category: "administrative",
      title: "Emergency Mode Operation Plan",
      objective: "Establish procedures to enable continuation of critical business processes during emergency mode.",
      evidencePackPrefixes: ["hipaa", "bcp"],
      meta: { standard: "164.308(a)(7) Contingency Plan", classification: "required" },
    },
    {
      id: "164.308(a)(7)(ii)(D)",
      category: "administrative",
      title: "Testing and Revision Procedures",
      objective: "Implement procedures for periodic testing and revision of contingency plans.",
      evidencePackPrefixes: ["hipaa", "dr"],
      meta: { standard: "164.308(a)(7) Contingency Plan", classification: "addressable" },
    },
    {
      id: "164.308(a)(8)",
      category: "administrative",
      title: "Evaluation",
      objective: "Perform a periodic technical and nontechnical evaluation of the security safeguards.",
      evidencePackPrefixes: ["hipaa"],
      meta: { standard: "164.308(a)(8) Evaluation", classification: "required" },
    },
    // ── physical ────────────────────────────────────────────────────
    {
      id: "164.310(a)(1)",
      category: "physical",
      title: "Facility Access Controls — Standard",
      objective: "Implement policies and procedures to limit physical access to electronic information systems.",
      evidencePackPrefixes: ["hipaa", "physical-security"],
      meta: { standard: "164.310(a)(1) Facility Access Controls", classification: "required" },
    },
    {
      id: "164.310(a)(2)(ii)",
      category: "physical",
      title: "Facility Security Plan",
      objective: "Implement policies to safeguard facility and equipment from unauthorized physical access.",
      evidencePackPrefixes: ["hipaa", "physical-security"],
      meta: { standard: "164.310(a)(1) Facility Access Controls", classification: "addressable" },
    },
    {
      id: "164.310(b)",
      category: "physical",
      title: "Workstation Use",
      objective: "Implement policies and procedures that specify the proper functions to be performed by workstations.",
      evidencePackPrefixes: ["hipaa", "endpoint"],
      meta: { standard: "164.310(b) Workstation Use", classification: "required" },
    },
    {
      id: "164.310(c)",
      category: "physical",
      title: "Workstation Security",
      objective: "Implement physical safeguards for all workstations that access ePHI.",
      evidencePackPrefixes: ["hipaa", "endpoint"],
      meta: { standard: "164.310(c) Workstation Security", classification: "required" },
    },
    {
      id: "164.310(d)(1)",
      category: "physical",
      title: "Device and Media Controls — Standard",
      objective: "Implement policies and procedures that govern the receipt and removal of hardware and electronic media that contain ePHI.",
      evidencePackPrefixes: ["hipaa", "asset-management"],
      meta: { standard: "164.310(d)(1) Device and Media Controls", classification: "required" },
    },
    {
      id: "164.310(d)(2)(i)",
      category: "physical",
      title: "Disposal",
      objective: "Implement policies and procedures to address the final disposition of ePHI.",
      evidencePackPrefixes: ["hipaa", "data-deletion"],
      meta: { standard: "164.310(d)(1) Device and Media Controls", classification: "required" },
    },
    {
      id: "164.310(d)(2)(ii)",
      category: "physical",
      title: "Media Re-use",
      objective: "Implement procedures for removal of ePHI before media is made available for re-use.",
      evidencePackPrefixes: ["hipaa", "data-deletion"],
      meta: { standard: "164.310(d)(1) Device and Media Controls", classification: "required" },
    },
    // ── technical ───────────────────────────────────────────────────
    {
      id: "164.312(a)(1)",
      category: "technical",
      title: "Access Control — Standard",
      objective: "Implement technical policies and procedures for electronic information systems that maintain ePHI to allow access only to those persons or software programs that have been granted access rights.",
      evidencePackPrefixes: ["hipaa", "iam", "rbac"],
      meta: { standard: "164.312(a)(1) Access Control", classification: "required" },
    },
    {
      id: "164.312(a)(2)(i)",
      category: "technical",
      title: "Unique User Identification",
      objective: "Assign a unique name and/or number for identifying and tracking user identity.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.312(a)(1) Access Control", classification: "required" },
    },
    {
      id: "164.312(a)(2)(ii)",
      category: "technical",
      title: "Emergency Access Procedure",
      objective: "Establish procedures for obtaining necessary ePHI during an emergency.",
      evidencePackPrefixes: ["hipaa", "iam"],
      meta: { standard: "164.312(a)(1) Access Control", classification: "required" },
    },
    {
      id: "164.312(a)(2)(iii)",
      category: "technical",
      title: "Automatic Logoff",
      objective: "Implement electronic procedures that terminate an electronic session after a predetermined time of inactivity.",
      evidencePackPrefixes: ["hipaa", "auth"],
      meta: { standard: "164.312(a)(1) Access Control", classification: "addressable" },
    },
    {
      id: "164.312(a)(2)(iv)",
      category: "technical",
      title: "Encryption and Decryption",
      objective: "Implement a mechanism to encrypt and decrypt ePHI.",
      evidencePackPrefixes: ["hipaa", "encryption"],
      meta: { standard: "164.312(a)(1) Access Control", classification: "addressable" },
    },
    {
      id: "164.312(b)",
      category: "technical",
      title: "Audit Controls",
      objective: "Implement hardware, software, and/or procedural mechanisms that record and examine activity in information systems that contain or use ePHI.",
      evidencePackPrefixes: ["hipaa", "audit-log", "vaos"],
      meta: { standard: "164.312(b) Audit Controls", classification: "required" },
    },
    {
      id: "164.312(c)(1)",
      category: "technical",
      title: "Integrity — Standard",
      objective: "Implement policies and procedures to protect ePHI from improper alteration or destruction.",
      evidencePackPrefixes: ["hipaa", "vaos", "integrity"],
      meta: { standard: "164.312(c)(1) Integrity", classification: "required" },
    },
    {
      id: "164.312(c)(2)",
      category: "technical",
      title: "Mechanism to Authenticate ePHI",
      objective: "Implement electronic mechanisms to corroborate that ePHI has not been altered or destroyed in an unauthorized manner.",
      evidencePackPrefixes: ["hipaa", "vaos", "integrity"],
      meta: { standard: "164.312(c)(1) Integrity", classification: "addressable" },
    },
    {
      id: "164.312(d)",
      category: "technical",
      title: "Person or Entity Authentication",
      objective: "Implement procedures to verify that a person or entity seeking access to ePHI is the one claimed.",
      evidencePackPrefixes: ["hipaa", "auth"],
      meta: { standard: "164.312(d) Person or Entity Authentication", classification: "required" },
    },
    {
      id: "164.312(e)(1)",
      category: "technical",
      title: "Transmission Security — Standard",
      objective: "Implement technical security measures to guard against unauthorized access to ePHI that is being transmitted over an electronic communications network.",
      evidencePackPrefixes: ["hipaa", "tls", "encryption"],
      meta: { standard: "164.312(e)(1) Transmission Security", classification: "required" },
    },
    {
      id: "164.312(e)(2)(i)",
      category: "technical",
      title: "Integrity Controls",
      objective: "Implement security measures to ensure that electronically transmitted ePHI is not improperly modified without detection until disposed of.",
      evidencePackPrefixes: ["hipaa", "tls", "vaos"],
      meta: { standard: "164.312(e)(1) Transmission Security", classification: "addressable" },
    },
    {
      id: "164.312(e)(2)(ii)",
      category: "technical",
      title: "Encryption",
      objective: "Implement a mechanism to encrypt ePHI whenever deemed appropriate.",
      evidencePackPrefixes: ["hipaa", "tls", "encryption"],
      meta: { standard: "164.312(e)(1) Transmission Security", classification: "addressable" },
    },
    // ── organizational ──────────────────────────────────────────────
    {
      id: "164.314(a)(1)",
      category: "organizational",
      title: "Business Associate Contracts",
      objective: "Have a contract or other arrangement that meets the applicable requirements with each business associate.",
      evidencePackPrefixes: ["hipaa", "vendor-management"],
      meta: { standard: "164.314(a)(1) Business Associate Contracts", classification: "required" },
    },
    {
      id: "164.314(b)(1)",
      category: "organizational",
      title: "Requirements for Group Health Plans",
      objective: "Group health plans must ensure plan documents provide that the sponsor will reasonably and appropriately safeguard ePHI.",
      evidencePackPrefixes: ["hipaa"],
      meta: { standard: "164.314(b)(1) Requirements for Group Health Plans", classification: "required" },
    },
    // ── policies ────────────────────────────────────────────────────
    {
      id: "164.316(a)",
      category: "policies",
      title: "Policies and Procedures",
      objective: "Implement reasonable and appropriate policies and procedures to comply with the standards.",
      evidencePackPrefixes: ["hipaa", "policy"],
      meta: { standard: "164.316(a) Policies and Procedures", classification: "required" },
    },
    {
      id: "164.316(b)(1)",
      category: "policies",
      title: "Documentation — Standard",
      objective: "Maintain the policies and procedures in written (which may be electronic) form, and document any action, activity, or assessment required to be documented.",
      evidencePackPrefixes: ["hipaa", "documentation"],
      meta: { standard: "164.316(b)(1) Documentation", classification: "required" },
    },
    {
      id: "164.316(b)(2)(i)",
      category: "policies",
      title: "Time Limit",
      objective: "Retain the documentation for 6 years from the date of its creation or the date when it last was in effect, whichever is later.",
      evidencePackPrefixes: ["hipaa", "retention"],
      meta: { standard: "164.316(b)(1) Documentation", classification: "required" },
    },
    {
      id: "164.316(b)(2)(ii)",
      category: "policies",
      title: "Availability",
      objective: "Make documentation available to those persons responsible for implementing the procedures.",
      evidencePackPrefixes: ["hipaa", "documentation"],
      meta: { standard: "164.316(b)(1) Documentation", classification: "addressable" },
    },
    {
      id: "164.316(b)(2)(iii)",
      category: "policies",
      title: "Updates",
      objective: "Review documentation periodically and update as needed.",
      evidencePackPrefixes: ["hipaa", "documentation"],
      meta: { standard: "164.316(b)(1) Documentation", classification: "addressable" },
    },
  ],
};
