/**
 * NIST AI Risk Management Framework 1.0 — NIST AI 100-1.
 *
 * Grouped by the four functions. Each subcategory also carries its
 * NIST category (GOVERN-1, MAP-2…) and the trustworthy-AI
 * characteristic it serves, both surfaced as report columns.
 *
 * 50 subcategories. Data only — the engine renders it.
 *
 * @packageDocumentation
 */

import type { RegulationPack } from "../types.js";

export const NIST_AI_RMF_PACK: RegulationPack = {
  id: "nist-ai-rmf",
  standard: "NIST AI RMF 1.0 (NIST AI 100-1, January 2023)",
  reportTitle: "NIST AI Risk Management Framework 1.0 — Profile Report",
  schema: "vaos-nist-ai-rmf-v1",
  preamble:
    "This report maps the NIST AI RMF 1.0 functions (GOVERN, MAP, MEASURE, MANAGE) and their subcategories to receipt-derived evidence. The AI RMF is voluntary guidance: this is a profile showing which outcomes are evidenced, not a conformity claim.",
  controlNoun: { singular: "subcategory", plural: "subcategories" },
  categories: [
    "GOVERN",
    "MAP",
    "MEASURE",
    "MANAGE",
  ],
  metaColumns: [
    { key: "category", header: "Category" },
    { key: "characteristic", header: "Characteristic" },
  ],
  controls: [
    // ── GOVERN ──────────────────────────────────────────────────────
    {
      id: "GOVERN-1.1",
      category: "GOVERN",
      title: "Legal and regulatory requirements involving AI are understood, managed, and documented.",
      objective: "Legal and regulatory requirements involving AI are understood, managed, and documented.",
      evidencePackPrefixes: ["nist-ai-rmf", "euaiact", "eu-ai-act", "iso42001"],
      meta: { characteristic: "accountable-and-transparent", category: "GOVERN-1" },
    },
    {
      id: "GOVERN-1.2",
      category: "GOVERN",
      title: "The characteristics of trustworthy AI are integrated into organizational policies.",
      objective: "The characteristics of trustworthy AI are integrated into organizational policies.",
      evidencePackPrefixes: ["nist-ai-rmf", "iso42001"],
      meta: { characteristic: "accountable-and-transparent", category: "GOVERN-1" },
    },
    {
      id: "GOVERN-1.3",
      category: "GOVERN",
      title: "Processes, procedures, and practices for AI risks are defined and documented.",
      objective: "Processes, procedures, and practices for AI risks are defined and documented.",
      evidencePackPrefixes: ["nist-ai-rmf", "iso42001"],
      meta: { characteristic: "accountable-and-transparent", category: "GOVERN-1" },
    },
    {
      id: "GOVERN-2.1",
      category: "GOVERN",
      title: "Roles and responsibilities related to AI risks are documented and communicated.",
      objective: "Roles and responsibilities related to AI risks are documented and communicated.",
      evidencePackPrefixes: ["nist-ai-rmf", "iso42001"],
      meta: { characteristic: "accountable-and-transparent", category: "GOVERN-2" },
    },
    {
      id: "GOVERN-3.2",
      category: "GOVERN",
      title: "Policies and procedures are in place to define and differentiate roles for human-AI configurations.",
      objective: "Policies and procedures are in place to define and differentiate roles for human-AI configurations.",
      evidencePackPrefixes: ["nist-ai-rmf", "human-in-loop"],
      meta: { characteristic: "accountable-and-transparent", category: "GOVERN-3" },
    },
    {
      id: "GOVERN-4.1",
      category: "GOVERN",
      title: "Organizational practices are in place to foster a critical thinking and safety-first mindset.",
      objective: "Organizational practices are in place to foster a critical thinking and safety-first mindset.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "safe", category: "GOVERN-4" },
    },
    {
      id: "GOVERN-4.2",
      category: "GOVERN",
      title: "Organizational teams document the risks and potential impacts of the AI technology they design.",
      objective: "Organizational teams document the risks and potential impacts of the AI technology they design.",
      evidencePackPrefixes: ["nist-ai-rmf", "iso42001", "euaiact", "eu-ai-act"],
      meta: { characteristic: "safe", category: "GOVERN-4" },
    },
    {
      id: "GOVERN-5.1",
      category: "GOVERN",
      title: "Mechanisms are in place to collect, consider, and prioritize input from AI actors.",
      objective: "Mechanisms are in place to collect, consider, and prioritize input from AI actors.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "accountable-and-transparent", category: "GOVERN-5" },
    },
    {
      id: "GOVERN-6.1",
      category: "GOVERN",
      title: "Policies and procedures are in place to address AI risks and benefits arising from third-party software and data.",
      objective: "Policies and procedures are in place to address AI risks and benefits arising from third-party software and data.",
      evidencePackPrefixes: ["nist-ai-rmf", "supply-chain", "owasp"],
      meta: { characteristic: "secure-and-resilient", category: "GOVERN-6" },
    },
    // ── MAP ─────────────────────────────────────────────────────────
    {
      id: "MAP-1.1",
      category: "MAP",
      title: "Intended purposes, potentially beneficial uses, context-specific laws, norms and expectations are understood and documented.",
      objective: "Intended purposes, potentially beneficial uses, context-specific laws, norms and expectations are understood and documented.",
      evidencePackPrefixes: ["nist-ai-rmf", "iso42001", "euaiact", "eu-ai-act"],
      meta: { characteristic: "accountable-and-transparent", category: "MAP-1" },
    },
    {
      id: "MAP-1.5",
      category: "MAP",
      title: "Organizational risk tolerances are determined and documented.",
      objective: "Organizational risk tolerances are determined and documented.",
      evidencePackPrefixes: ["nist-ai-rmf", "iso42001"],
      meta: { characteristic: "accountable-and-transparent", category: "MAP-1" },
    },
    {
      id: "MAP-2.1",
      category: "MAP",
      title: "The specific task and the methods used to implement the task are defined.",
      objective: "The specific task and the methods used to implement the task are defined.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MAP-2" },
    },
    {
      id: "MAP-2.2",
      category: "MAP",
      title: "Information about the AI system's knowledge limits and how outputs may be utilized is documented.",
      objective: "Information about the AI system's knowledge limits and how outputs may be utilized is documented.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "explainable-and-interpretable", category: "MAP-2" },
    },
    {
      id: "MAP-3.1",
      category: "MAP",
      title: "Potential benefits of intended AI system functionality and performance are examined and documented.",
      objective: "Potential benefits of intended AI system functionality and performance are examined and documented.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MAP-3" },
    },
    {
      id: "MAP-3.4",
      category: "MAP",
      title: "Processes for operator and practitioner proficiency with AI system performance and trustworthiness are defined.",
      objective: "Processes for operator and practitioner proficiency with AI system performance and trustworthiness are defined.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MAP-3" },
    },
    {
      id: "MAP-4.1",
      category: "MAP",
      title: "Approaches for mapping AI technology and legal risks of components are defined.",
      objective: "Approaches for mapping AI technology and legal risks of components are defined.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "accountable-and-transparent", category: "MAP-4" },
    },
    {
      id: "MAP-5.1",
      category: "MAP",
      title: "Likelihood and magnitude of each identified impact (positive and negative) are identified.",
      objective: "Likelihood and magnitude of each identified impact (positive and negative) are identified.",
      evidencePackPrefixes: ["nist-ai-rmf", "owasp"],
      meta: { characteristic: "safe", category: "MAP-5" },
    },
    // ── MEASURE ─────────────────────────────────────────────────────
    {
      id: "MEASURE-1.1",
      category: "MEASURE",
      title: "Approaches and metrics for measurement of AI risks are selected.",
      objective: "Approaches and metrics for measurement of AI risks are selected.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-1" },
    },
    {
      id: "MEASURE-2.1",
      category: "MEASURE",
      title: "Test sets, metrics, and details about the tools used during test, evaluation, validation, and verification are documented.",
      objective: "Test sets, metrics, and details about the tools used during test, evaluation, validation, and verification are documented.",
      evidencePackPrefixes: ["nist-ai-rmf", "owasp", "red-team"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.2",
      category: "MEASURE",
      title: "Evaluations involving human subjects meet applicable requirements and are representative of the relevant population.",
      objective: "Evaluations involving human subjects meet applicable requirements and are representative of the relevant population.",
      evidencePackPrefixes: ["nist-ai-rmf", "fairness"],
      meta: { characteristic: "fair-with-bias-managed", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.3",
      category: "MEASURE",
      title: "AI system performance or assurance criteria are measured qualitatively or quantitatively.",
      objective: "AI system performance or assurance criteria are measured qualitatively or quantitatively.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.4",
      category: "MEASURE",
      title: "The functionality and behavior of the AI system are monitored when in production.",
      objective: "The functionality and behavior of the AI system are monitored when in production.",
      evidencePackPrefixes: ["nist-ai-rmf", "iso42001"],
      meta: { characteristic: "safe", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.5",
      category: "MEASURE",
      title: "The AI system to be deployed is demonstrated to be valid and reliable.",
      objective: "The AI system to be deployed is demonstrated to be valid and reliable.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.6",
      category: "MEASURE",
      title: "The AI system is evaluated regularly for safety risks.",
      objective: "The AI system is evaluated regularly for safety risks.",
      evidencePackPrefixes: ["nist-ai-rmf", "owasp"],
      meta: { characteristic: "safe", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.7",
      category: "MEASURE",
      title: "AI system security and resilience are evaluated and documented.",
      objective: "AI system security and resilience are evaluated and documented.",
      evidencePackPrefixes: ["nist-ai-rmf", "owasp", "red-team"],
      meta: { characteristic: "secure-and-resilient", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.8",
      category: "MEASURE",
      title: "Risks associated with transparency and accountability are measured.",
      objective: "Risks associated with transparency and accountability are measured.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "accountable-and-transparent", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.9",
      category: "MEASURE",
      title: "The AI model is explained, validated, and documented, and AI system output is interpreted within its context.",
      objective: "The AI model is explained, validated, and documented, and AI system output is interpreted within its context.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "explainable-and-interpretable", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.10",
      category: "MEASURE",
      title: "Privacy risk of the AI system is examined and documented.",
      objective: "Privacy risk of the AI system is examined and documented.",
      evidencePackPrefixes: ["nist-ai-rmf", "gdpr", "popia", "hipaa"],
      meta: { characteristic: "privacy-enhanced", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.11",
      category: "MEASURE",
      title: "Fairness and bias — as identified in MAP function — are evaluated and results are documented.",
      objective: "Fairness and bias — as identified in MAP function — are evaluated and results are documented.",
      evidencePackPrefixes: ["nist-ai-rmf", "fairness"],
      meta: { characteristic: "fair-with-bias-managed", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.12",
      category: "MEASURE",
      title: "Environmental impact and sustainability of AI model training and management activities are assessed and documented.",
      objective: "Environmental impact and sustainability of AI model training and management activities are assessed and documented.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-2.13",
      category: "MEASURE",
      title: "Effectiveness of the employed TEVV metrics and processes is evaluated.",
      objective: "Effectiveness of the employed TEVV metrics and processes is evaluated.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-2" },
    },
    {
      id: "MEASURE-3.1",
      category: "MEASURE",
      title: "Approaches, personnel, and documentation are in place to regularly identify and track existing, unanticipated, and emergent AI risks.",
      objective: "Approaches, personnel, and documentation are in place to regularly identify and track existing, unanticipated, and emergent AI risks.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "safe", category: "MEASURE-3" },
    },
    {
      id: "MEASURE-3.2",
      category: "MEASURE",
      title: "Risk tracking approaches are considered for settings where AI risks are difficult to assess using currently available measurement techniques.",
      objective: "Risk tracking approaches are considered for settings where AI risks are difficult to assess using currently available measurement techniques.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "safe", category: "MEASURE-3" },
    },
    {
      id: "MEASURE-3.3",
      category: "MEASURE",
      title: "Feedback processes for end users and impacted communities to report problems and appeal system outcomes are established and integrated into AI system evaluation metrics.",
      objective: "Feedback processes for end users and impacted communities to report problems and appeal system outcomes are established and integrated into AI system evaluation metrics.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "accountable-and-transparent", category: "MEASURE-3" },
    },
    {
      id: "MEASURE-4.1",
      category: "MEASURE",
      title: "Measurement approaches for identifying AI risks are connected to deployment context(s) and informed through consultation with domain experts and other end users.",
      objective: "Measurement approaches for identifying AI risks are connected to deployment context(s) and informed through consultation with domain experts and other end users.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-4" },
    },
    {
      id: "MEASURE-4.2",
      category: "MEASURE",
      title: "Measurement results regarding AI system trustworthiness in deployment context(s) and across the AI lifecycle are informed by input from domain experts and relevant AI actors to validate whether the system is performing consistently.",
      objective: "Measurement results regarding AI system trustworthiness in deployment context(s) and across the AI lifecycle are informed by input from domain experts and relevant AI actors to validate whether the system is performing consistently.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-4" },
    },
    {
      id: "MEASURE-4.3",
      category: "MEASURE",
      title: "Measurable performance improvements or declines based on consultations with relevant AI actors, including affected communities, and field data are identified and documented.",
      objective: "Measurable performance improvements or declines based on consultations with relevant AI actors, including affected communities, and field data are identified and documented.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MEASURE-4" },
    },
    // ── MANAGE ──────────────────────────────────────────────────────
    {
      id: "MANAGE-1.1",
      category: "MANAGE",
      title: "A determination is made as to whether the AI system achieves its intended purposes and stated objectives and whether its development or deployment should proceed.",
      objective: "A determination is made as to whether the AI system achieves its intended purposes and stated objectives and whether its development or deployment should proceed.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MANAGE-1" },
    },
    {
      id: "MANAGE-1.2",
      category: "MANAGE",
      title: "Treatment of documented AI risks is prioritized based on impact, likelihood, and available resources or methods.",
      objective: "Treatment of documented AI risks is prioritized based on impact, likelihood, and available resources or methods.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "safe", category: "MANAGE-1" },
    },
    {
      id: "MANAGE-1.3",
      category: "MANAGE",
      title: "Responses to the AI risks deemed high priority, as identified by the MAP function, are developed, planned, and documented.",
      objective: "Responses to the AI risks deemed high priority, as identified by the MAP function, are developed, planned, and documented.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "safe", category: "MANAGE-1" },
    },
    {
      id: "MANAGE-1.4",
      category: "MANAGE",
      title: "Negative residual risks (defined as risks remaining after risk treatment) to both downstream acquirers of AI systems and end users are documented.",
      objective: "Negative residual risks (defined as risks remaining after risk treatment) to both downstream acquirers of AI systems and end users are documented.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "safe", category: "MANAGE-1" },
    },
    {
      id: "MANAGE-2.1",
      category: "MANAGE",
      title: "Resources required to manage AI risks are taken into account.",
      objective: "Resources required to manage AI risks are taken into account.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "safe", category: "MANAGE-2" },
    },
    {
      id: "MANAGE-2.2",
      category: "MANAGE",
      title: "Mechanisms are in place and applied to sustain the value of deployed AI systems.",
      objective: "Mechanisms are in place and applied to sustain the value of deployed AI systems.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MANAGE-2" },
    },
    {
      id: "MANAGE-2.3",
      category: "MANAGE",
      title: "Procedures are followed to respond to and recover from a previously unknown risk when it is identified.",
      objective: "Procedures are followed to respond to and recover from a previously unknown risk when it is identified.",
      evidencePackPrefixes: ["nist-ai-rmf", "incident-response"],
      meta: { characteristic: "secure-and-resilient", category: "MANAGE-2" },
    },
    {
      id: "MANAGE-2.4",
      category: "MANAGE",
      title: "Mechanisms are in place and applied, and responsibilities are assigned and understood, to supersede, disengage, or deactivate AI systems that demonstrate performance or outcomes inconsistent with intended use.",
      objective: "Mechanisms are in place and applied, and responsibilities are assigned and understood, to supersede, disengage, or deactivate AI systems that demonstrate performance or outcomes inconsistent with intended use.",
      evidencePackPrefixes: ["nist-ai-rmf", "kill-switch"],
      meta: { characteristic: "safe", category: "MANAGE-2" },
    },
    {
      id: "MANAGE-3.1",
      category: "MANAGE",
      title: "AI risks and benefits from third-party resources are regularly monitored.",
      objective: "AI risks and benefits from third-party resources are regularly monitored.",
      evidencePackPrefixes: ["nist-ai-rmf", "supply-chain"],
      meta: { characteristic: "secure-and-resilient", category: "MANAGE-3" },
    },
    {
      id: "MANAGE-3.2",
      category: "MANAGE",
      title: "Pre-trained models which are used for development are monitored as part of AI system regular monitoring and maintenance.",
      objective: "Pre-trained models which are used for development are monitored as part of AI system regular monitoring and maintenance.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "secure-and-resilient", category: "MANAGE-3" },
    },
    {
      id: "MANAGE-4.1",
      category: "MANAGE",
      title: "Post-deployment AI system monitoring plans are implemented, including mechanisms for capturing and evaluating input from users and other relevant AI actors.",
      objective: "Post-deployment AI system monitoring plans are implemented, including mechanisms for capturing and evaluating input from users and other relevant AI actors.",
      evidencePackPrefixes: ["nist-ai-rmf", "iso42001"],
      meta: { characteristic: "safe", category: "MANAGE-4" },
    },
    {
      id: "MANAGE-4.2",
      category: "MANAGE",
      title: "Measurable activities for continual improvements are integrated into AI system updates and include regular engagement with interested parties.",
      objective: "Measurable activities for continual improvements are integrated into AI system updates and include regular engagement with interested parties.",
      evidencePackPrefixes: ["nist-ai-rmf"],
      meta: { characteristic: "valid-and-reliable", category: "MANAGE-4" },
    },
    {
      id: "MANAGE-4.3",
      category: "MANAGE",
      title: "Incidents and errors are communicated to relevant AI actors including affected communities.",
      objective: "Incidents and errors are communicated to relevant AI actors including affected communities.",
      evidencePackPrefixes: ["nist-ai-rmf", "incident-response"],
      meta: { characteristic: "accountable-and-transparent", category: "MANAGE-4" },
    },
  ],
};
