/**
 * SOC 2 — AICPA Trust Services Criteria.
 *
 * Security (the common criteria, CC1–CC9) is always in scope; the
 * other four categories are opt-in via `scope.inScope`, which is how
 * SOC 2 engagements are actually scoped.
 *
 * 51 criteria. Data only — the engine renders it.
 *
 * @packageDocumentation
 */

import type { RegulationPack } from "../types.js";

export const SOC2_PACK: RegulationPack = {
  id: "soc2",
  standard: "AICPA Trust Services Criteria (2017)",
  reportTitle: "SOC 2 Evidence Binder",
  schema: "vaos-soc2-evidence-v1",
  preamble:
    "This binder maps AICPA Trust Services Criteria (2017) to receipt-derived evidence over the audit period. Hand it to your CPA firm as Period of Performance evidence under AT-C § 105 / SSAE 21. It is evidence for an audit, not an audit opinion.",
  controlNoun: { singular: "criterion", plural: "criteria" },
  categories: [
    "security",
    "availability",
    "processing-integrity",
    "confidentiality",
    "privacy",
  ],
  alwaysInScope: ["security"],
  controls: [
    // ── security ────────────────────────────────────────────────────
    {
      id: "CC1.1",
      category: "security",
      title: "Control Environment — Integrity and Ethical Values",
      objective: "The entity demonstrates a commitment to integrity and ethical values.",
      evidencePackPrefixes: ["soc2", "ethics", "code-of-conduct"],
    },
    {
      id: "CC1.2",
      category: "security",
      title: "Control Environment — Board Oversight",
      objective: "The board of directors demonstrates independence from management and exercises oversight of internal control.",
      evidencePackPrefixes: ["soc2", "governance"],
    },
    {
      id: "CC1.3",
      category: "security",
      title: "Control Environment — Organizational Structure",
      objective: "Management establishes structures, reporting lines, and appropriate authorities and responsibilities.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC1.4",
      category: "security",
      title: "Control Environment — Personnel Competence",
      objective: "The entity demonstrates a commitment to attract, develop, and retain competent individuals.",
      evidencePackPrefixes: ["soc2", "hr"],
    },
    {
      id: "CC1.5",
      category: "security",
      title: "Control Environment — Accountability",
      objective: "The entity holds individuals accountable for their internal control responsibilities.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC2.1",
      category: "security",
      title: "Communication and Information — Information Quality",
      objective: "The entity obtains or generates and uses relevant, quality information to support the functioning of internal control.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC2.2",
      category: "security",
      title: "Communication and Information — Internal Communication",
      objective: "The entity internally communicates information necessary to support the functioning of internal control.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC2.3",
      category: "security",
      title: "Communication and Information — External Communication",
      objective: "The entity communicates with external parties regarding matters affecting the functioning of internal control.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC3.1",
      category: "security",
      title: "Risk Assessment — Objectives",
      objective: "The entity specifies objectives with sufficient clarity to enable the identification and assessment of risks.",
      evidencePackPrefixes: ["soc2", "risk-assessment"],
    },
    {
      id: "CC3.2",
      category: "security",
      title: "Risk Assessment — Risk Identification",
      objective: "The entity identifies risks to the achievement of its objectives and analyzes risks as a basis for determining how the risks should be managed.",
      evidencePackPrefixes: ["soc2", "risk-assessment", "owasp"],
    },
    {
      id: "CC3.3",
      category: "security",
      title: "Risk Assessment — Fraud Risk",
      objective: "The entity considers the potential for fraud in assessing risks to the achievement of objectives.",
      evidencePackPrefixes: ["soc2", "fraud", "anomaly"],
    },
    {
      id: "CC3.4",
      category: "security",
      title: "Risk Assessment — Change Identification",
      objective: "The entity identifies and assesses changes that could significantly impact the system of internal control.",
      evidencePackPrefixes: ["soc2", "change-management"],
    },
    {
      id: "CC4.1",
      category: "security",
      title: "Monitoring Activities — Ongoing Evaluations",
      objective: "The entity selects, develops, and performs ongoing and/or separate evaluations to ascertain whether the components of internal control are present and functioning.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC4.2",
      category: "security",
      title: "Monitoring Activities — Deficiency Evaluation",
      objective: "The entity evaluates and communicates internal control deficiencies in a timely manner.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC5.1",
      category: "security",
      title: "Control Activities — Selection and Development",
      objective: "The entity selects and develops control activities that contribute to the mitigation of risks.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC5.2",
      category: "security",
      title: "Control Activities — Technology Controls",
      objective: "The entity selects and develops general control activities over technology to support the achievement of objectives.",
      evidencePackPrefixes: ["soc2", "technology-controls"],
    },
    {
      id: "CC5.3",
      category: "security",
      title: "Control Activities — Policies and Procedures",
      objective: "The entity deploys control activities through policies that establish what is expected and procedures that put policies into action.",
      evidencePackPrefixes: ["soc2"],
    },
    {
      id: "CC6.1",
      category: "security",
      title: "Logical and Physical Access Controls — Logical Access",
      objective: "The entity implements logical access security software, infrastructure, and architectures over protected information assets.",
      evidencePackPrefixes: ["soc2", "auth", "rbac", "iam"],
    },
    {
      id: "CC6.2",
      category: "security",
      title: "Logical and Physical Access Controls — Access Authorization",
      objective: "Prior to issuing system credentials, the entity registers and authorizes new internal and external users.",
      evidencePackPrefixes: ["soc2", "auth", "iam"],
    },
    {
      id: "CC6.3",
      category: "security",
      title: "Logical and Physical Access Controls — Access Modification",
      objective: "The entity authorizes, modifies, or removes access to data, software, functions, and other protected information assets.",
      evidencePackPrefixes: ["soc2", "iam"],
    },
    {
      id: "CC6.4",
      category: "security",
      title: "Logical and Physical Access Controls — Physical Access",
      objective: "The entity restricts physical access to facilities and protected information assets.",
      evidencePackPrefixes: ["soc2", "physical-security"],
    },
    {
      id: "CC6.5",
      category: "security",
      title: "Logical and Physical Access Controls — Asset Disposal",
      objective: "The entity discontinues logical and physical protections over physical assets only after the ability to read or recover data and software from those assets has been diminished.",
      evidencePackPrefixes: ["soc2", "asset-management"],
    },
    {
      id: "CC6.6",
      category: "security",
      title: "Logical and Physical Access Controls — External Threats",
      objective: "The entity implements logical access security measures to protect against threats from sources outside its system boundaries.",
      evidencePackPrefixes: ["soc2", "firewall", "waf"],
    },
    {
      id: "CC6.7",
      category: "security",
      title: "Logical and Physical Access Controls — Data Transmission",
      objective: "The entity restricts the transmission, movement, and removal of information.",
      evidencePackPrefixes: ["soc2", "encryption", "tls"],
    },
    {
      id: "CC6.8",
      category: "security",
      title: "Logical and Physical Access Controls — Malicious Software Prevention",
      objective: "The entity implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software.",
      evidencePackPrefixes: ["soc2", "antivirus", "supply-chain"],
    },
    {
      id: "CC7.1",
      category: "security",
      title: "System Operations — Configuration Vulnerabilities",
      objective: "To meet its objectives, the entity uses detection and monitoring procedures to identify changes to configurations that result in the introduction of new vulnerabilities.",
      evidencePackPrefixes: ["soc2", "vuln-scan", "owasp"],
    },
    {
      id: "CC7.2",
      category: "security",
      title: "System Operations — Anomaly Monitoring",
      objective: "The entity monitors system components and the operation of those components for anomalies that are indicative of malicious acts, natural disasters, and errors.",
      evidencePackPrefixes: ["soc2", "anomaly"],
    },
    {
      id: "CC7.3",
      category: "security",
      title: "System Operations — Security Event Evaluation",
      objective: "The entity evaluates security events to determine whether they could or have resulted in a failure of the entity to meet its objectives and, if so, takes actions to prevent or address such failures.",
      evidencePackPrefixes: ["soc2", "siem"],
    },
    {
      id: "CC7.4",
      category: "security",
      title: "System Operations — Incident Response",
      objective: "The entity responds to identified security incidents by executing a defined incident response program to understand, contain, remediate, and communicate security incidents, as appropriate.",
      evidencePackPrefixes: ["soc2", "incident-response"],
    },
    {
      id: "CC7.5",
      category: "security",
      title: "System Operations — Incident Recovery",
      objective: "The entity identifies, develops, and implements activities to recover from identified security incidents.",
      evidencePackPrefixes: ["soc2", "incident-response", "dr"],
    },
    {
      id: "CC8.1",
      category: "security",
      title: "Change Management",
      objective: "The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures.",
      evidencePackPrefixes: ["soc2", "change-management"],
    },
    {
      id: "CC9.1",
      category: "security",
      title: "Risk Mitigation — Risk Mitigation Activities",
      objective: "The entity identifies, selects, and develops risk mitigation activities for risks arising from potential business disruptions.",
      evidencePackPrefixes: ["soc2", "bcp", "dr"],
    },
    {
      id: "CC9.2",
      category: "security",
      title: "Risk Mitigation — Vendor and Business Partner Management",
      objective: "The entity assesses and manages risks associated with vendors and business partners.",
      evidencePackPrefixes: ["soc2", "vendor-management", "supply-chain"],
    },
    // ── availability ────────────────────────────────────────────────
    {
      id: "A1.1",
      category: "availability",
      title: "Availability — Capacity",
      objective: "The entity maintains, monitors, and evaluates current processing capacity and use of system components to manage capacity demand.",
      evidencePackPrefixes: ["soc2", "availability", "capacity"],
    },
    {
      id: "A1.2",
      category: "availability",
      title: "Availability — Environmental Protection",
      objective: "The entity authorizes, designs, develops or acquires, implements, operates, approves, maintains, and monitors environmental protections, software, data backup processes, and recovery infrastructure to meet its objectives.",
      evidencePackPrefixes: ["soc2", "availability", "backup"],
    },
    {
      id: "A1.3",
      category: "availability",
      title: "Availability — Recovery Testing",
      objective: "The entity tests recovery plan procedures supporting system recovery to meet its objectives.",
      evidencePackPrefixes: ["soc2", "dr"],
    },
    // ── processing-integrity ────────────────────────────────────────
    {
      id: "PI1.1",
      category: "processing-integrity",
      title: "Processing Integrity — System Inputs",
      objective: "The entity obtains or generates, uses, and communicates relevant, quality information regarding the objectives related to processing.",
      evidencePackPrefixes: ["soc2", "processing-integrity"],
    },
    {
      id: "PI1.2",
      category: "processing-integrity",
      title: "Processing Integrity — System Inputs Are Complete",
      objective: "The entity implements policies and procedures over system inputs, including controls over completeness and accuracy.",
      evidencePackPrefixes: ["soc2", "processing-integrity", "validation"],
    },
    {
      id: "PI1.3",
      category: "processing-integrity",
      title: "Processing Integrity — System Processing",
      objective: "The entity implements policies and procedures over system processing to result in products, services, and reporting to meet the entity's objectives.",
      evidencePackPrefixes: ["soc2", "processing-integrity"],
    },
    {
      id: "PI1.4",
      category: "processing-integrity",
      title: "Processing Integrity — System Outputs",
      objective: "The entity implements policies and procedures to make available or deliver output completely, accurately, and timely in accordance with specifications.",
      evidencePackPrefixes: ["soc2", "processing-integrity"],
    },
    {
      id: "PI1.5",
      category: "processing-integrity",
      title: "Processing Integrity — Stored Items",
      objective: "The entity implements policies and procedures to store inputs, items in processing, and outputs completely, accurately, and timely in accordance with specifications.",
      evidencePackPrefixes: ["soc2", "processing-integrity", "vaos"],
    },
    // ── confidentiality ─────────────────────────────────────────────
    {
      id: "C1.1",
      category: "confidentiality",
      title: "Confidentiality — Identification and Maintenance",
      objective: "The entity identifies and maintains confidential information to meet the entity's objectives related to confidentiality.",
      evidencePackPrefixes: ["soc2", "confidentiality", "data-classification"],
    },
    {
      id: "C1.2",
      category: "confidentiality",
      title: "Confidentiality — Disposal",
      objective: "The entity disposes of confidential information to meet the entity's objectives related to confidentiality.",
      evidencePackPrefixes: ["soc2", "confidentiality", "data-deletion"],
    },
    // ── privacy ─────────────────────────────────────────────────────
    {
      id: "P1.1",
      category: "privacy",
      title: "Privacy — Notice",
      objective: "The entity provides notice to data subjects about its privacy practices.",
      evidencePackPrefixes: ["soc2", "privacy", "gdpr", "popia"],
    },
    {
      id: "P2.1",
      category: "privacy",
      title: "Privacy — Choice and Consent",
      objective: "The entity communicates choices available regarding the collection, use, retention, disclosure, and disposal of personal information.",
      evidencePackPrefixes: ["soc2", "privacy", "gdpr", "consent"],
    },
    {
      id: "P3.1",
      category: "privacy",
      title: "Privacy — Collection",
      objective: "Personal information is collected consistent with the entity's objectives related to privacy.",
      evidencePackPrefixes: ["soc2", "privacy", "gdpr"],
    },
    {
      id: "P4.1",
      category: "privacy",
      title: "Privacy — Use",
      objective: "The entity limits the use of personal information to the purposes identified in the entity's objectives.",
      evidencePackPrefixes: ["soc2", "privacy", "gdpr"],
    },
    {
      id: "P5.1",
      category: "privacy",
      title: "Privacy — Access",
      objective: "The entity grants identified and authenticated data subjects the ability to access their personal information.",
      evidencePackPrefixes: ["soc2", "privacy", "gdpr-art-15"],
    },
    {
      id: "P6.1",
      category: "privacy",
      title: "Privacy — Disclosure and Notification",
      objective: "The entity discloses personal information to third parties consistent with the entity's objectives related to privacy.",
      evidencePackPrefixes: ["soc2", "privacy"],
    },
    {
      id: "P7.1",
      category: "privacy",
      title: "Privacy — Quality",
      objective: "The entity collects and maintains accurate, up-to-date, complete, and relevant personal information.",
      evidencePackPrefixes: ["soc2", "privacy"],
    },
    {
      id: "P8.1",
      category: "privacy",
      title: "Privacy — Monitoring and Enforcement",
      objective: "The entity implements a process for receiving, addressing, resolving, and communicating the resolution of inquiries, complaints, and disputes from data subjects.",
      evidencePackPrefixes: ["soc2", "privacy"],
    },
  ],
};
