import { auth } from "@clerk/nextjs/server";
import { redirect, notFound } from "next/navigation";
import { getPacketById, type PacketKind } from "@/lib/packet-store";

/**
 * /dashboard/packets/[id]/print — print-optimised view.
 *
 * Server-rendered, ownership-checked, completely free of dark-mode chrome.
 * Cmd+P / Ctrl+P → "Save as PDF" → user gets a clean white-paper PDF
 * suitable for handing to a client (whitelabel-ready paper).
 *
 * Avoiding a heavy PDF library (puppeteer, react-pdf) by leaning on the
 * browser's native print engine — same path that produces every other
 * "Save as PDF" experience the user already knows.
 */

const KIND_LABEL: Record<PacketKind, string> = {
  "agency-content-packet": "Agency Content Packet",
  "recruiting-sourcing-sprint": "Recruiting Sourcing Sprint",
  "growth-pulse": "Growth Pulse",
  "listing-pulse": "Listing Pulse",
};

function get<T = unknown>(obj: unknown, key: string): T | undefined {
  if (
    obj &&
    typeof obj === "object" &&
    key in (obj as Record<string, unknown>)
  ) {
    return (obj as Record<string, unknown>)[key] as T;
  }
  return undefined;
}
const getStr = (o: unknown, k: string) => get<string>(o, k);
const getObj = (o: unknown, k: string) => get<Record<string, unknown>>(o, k);
const getArr = (o: unknown, k: string) => {
  const v = get<unknown[]>(o, k);
  return Array.isArray(v) ? v : undefined;
};

export default async function PacketPrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { userId } = await auth();
  const { id } = await params;
  if (!userId) {
    redirect(`/login?redirect=/dashboard/packets/${id}/print`);
  }
  const packet = await getPacketById(userId, id);
  if (!packet) notFound();

  const created = new Date(packet.createdAt);
  const createdLabel = Number.isNaN(created.getTime())
    ? packet.createdAt
    : created.toLocaleString();

  return (
    <html lang="en">
      <head>
        <title>{KIND_LABEL[packet.kind]} — print</title>
        <meta name="robots" content="noindex" />
        <style>{PRINT_STYLES}</style>
      </head>
      <body>
        <div className="paper">
          <header className="head">
            <div className="brand">Sovereign Matrix</div>
            <div className="meta">
              {KIND_LABEL[packet.kind]} · {createdLabel}
            </div>
          </header>

          <h1 className="title">
            {titleFromInput(packet.input) || "Saved packet"}
          </h1>

          {/* Vertical-specific body */}
          {packet.kind === "agency-content-packet" ? (
            <AgencyPaper output={packet.output} />
          ) : null}
          {packet.kind === "recruiting-sourcing-sprint" ? (
            <SourcingPaper output={packet.output} />
          ) : null}
          {packet.kind === "growth-pulse" ? (
            <GrowthPaper output={packet.output} />
          ) : null}
          {packet.kind === "listing-pulse" ? (
            <ListingPaper output={packet.output} />
          ) : null}

          <footer className="foot">
            <span>Generated by sovereignmatrix.agency</span>
            <span>{packet.id.slice(0, 8)}</span>
          </footer>
        </div>
      </body>
    </html>
  );
}

function titleFromInput(input: unknown): string | undefined {
  return (
    getStr(input, "clientName") ||
    getStr(input, "businessName") ||
    getStr(input, "companyName") ||
    getStr(input, "propertyAddress")
  );
}

// ─── Vertical paper renderers ──────────────────────────────────────────

function AgencyPaper({ output }: { output: unknown }) {
  const blog = getObj(output, "blog");
  const seq = getObj(output, "emailSequence");
  const ads = getArr(output, "ads");
  return (
    <>
      {blog ? (
        <section className="block">
          <h2>{getStr(blog, "title")}</h2>
          <div className="muted small">
            {getStr(blog, "wordCount")} words · meta:{" "}
            {getStr(blog, "metaDescription")}
          </div>
          <pre className="prose">{getStr(blog, "body")}</pre>
        </section>
      ) : null}
      {seq ? (
        <section className="block">
          <h2>Email sequence — {getStr(seq, "sequenceName")}</h2>
          {getArr(seq, "emails")?.map((e, i) => (
            <article key={`em-${i}`} className="email">
              <h3>
                Email {getStr(e, "stepNumber")} — day +{getStr(e, "delayDays")}
              </h3>
              <p className="subject">Subject: {getStr(e, "subject")}</p>
              <pre className="prose">{getStr(e, "body")}</pre>
            </article>
          ))}
        </section>
      ) : null}
      {ads ? (
        <section className="block">
          <h2>Ad creatives</h2>
          {ads.map((a, i) => (
            <article key={`ad-${i}`} className="email">
              <h3>{getStr(a, "platform")}</h3>
              <p className="subject">{getStr(a, "headline")}</p>
              <pre className="prose">{getStr(a, "primaryText")}</pre>
              <p className="muted small">CTA: {getStr(a, "callToAction")}</p>
            </article>
          ))}
        </section>
      ) : null}
    </>
  );
}

function SourcingPaper({ output }: { output: unknown }) {
  const icp = getObj(output, "icp");
  const booleans = getObj(output, "booleans");
  const outreach = getObj(output, "outreach");
  const channels = getArr(output, "channels");
  const objections = getArr(output, "objections");
  return (
    <>
      {icp ? (
        <section className="block">
          <h2>Ideal candidate profile — {getStr(icp, "archetype")}</h2>
          <p>
            <strong>Years:</strong> {getStr(icp, "yearsExperienceMin")}–
            {getStr(icp, "yearsExperienceMax")}
          </p>
          <h3>Must-have signals</h3>
          <ul>
            {getArr(icp, "mustHaveSignals")?.map((s, i) => (
              <li key={`ms-${i}`}>{String(s)}</li>
            ))}
          </ul>
          <h3>Motivators</h3>
          <ul>
            {getArr(icp, "motivators")?.map((s, i) => (
              <li key={`mt-${i}`}>{String(s)}</li>
            ))}
          </ul>
        </section>
      ) : null}
      {booleans ? (
        <section className="block">
          <h2>Boolean searches</h2>
          {(["linkedin", "googleXRay", "github"] as const).map((k) => {
            const v = getStr(booleans, k);
            if (!v) return null;
            return (
              <article key={k} className="email">
                <h3>{k === "googleXRay" ? "Google X-Ray" : k}</h3>
                <pre className="prose mono">{v}</pre>
              </article>
            );
          })}
        </section>
      ) : null}
      {outreach ? (
        <section className="block">
          <h2>Outreach pack</h2>
          <article className="email">
            <h3>LinkedIn DM</h3>
            <pre className="prose">
              {getStr(getObj(outreach, "linkedinDm"), "body")}
            </pre>
          </article>
          <article className="email">
            <h3>Cold email</h3>
            <p className="subject">
              Subject: {getStr(getObj(outreach, "coldEmail"), "subject")}
            </p>
            <pre className="prose">
              {getStr(getObj(outreach, "coldEmail"), "body")}
            </pre>
          </article>
          <article className="email">
            <h3>Voicemail script</h3>
            <pre className="prose">
              {getStr(getObj(outreach, "voicemail"), "script")}
            </pre>
          </article>
        </section>
      ) : null}
      {channels ? (
        <section className="block">
          <h2>Sourcing channels</h2>
          <ol>
            {channels.map((c, i) => (
              <li key={`ch-${i}`}>
                <strong>{getStr(c, "channel")}.</strong> {getStr(c, "why")}{" "}
                <em>First action: {getStr(c, "firstAction")}</em>
              </li>
            ))}
          </ol>
        </section>
      ) : null}
      {objections ? (
        <section className="block">
          <h2>Objection playbook</h2>
          {objections.map((o, i) => (
            <article key={`obj-${i}`} className="email">
              <p className="subject">&ldquo;{getStr(o, "objection")}&rdquo;</p>
              <p>
                <strong>Reply:</strong> {getStr(o, "response")}
              </p>
              <p className="muted small">
                If still cold: {getStr(o, "escalation")}
              </p>
            </article>
          ))}
        </section>
      ) : null}
    </>
  );
}

function GrowthPaper({ output }: { output: unknown }) {
  const seo = getObj(output, "seo");
  const social = getArr(output, "socialPosts");
  const email = getObj(output, "reEngagementEmail");
  const wa = getObj(output, "whatsapp");
  const offer = getObj(output, "offer");
  return (
    <>
      {seo ? (
        <section className="block">
          <h2>Local-SEO checklist</h2>
          <p>
            <strong>Priority fix:</strong> {getStr(seo, "priorityFix")}
          </p>
          <ol>
            {getArr(seo, "items")?.map((it, i) => (
              <li key={`seo-${i}`}>
                <strong>{getStr(it, "task")}</strong> — {getStr(it, "why")}{" "}
                <span className="muted small">
                  (~{getStr(it, "estimatedMinutes")}m)
                </span>
              </li>
            ))}
          </ol>
          <p className="muted">
            <strong>Local keywords:</strong>{" "}
            {getArr(seo, "localKeywords")?.map(String).join(", ")}
          </p>
        </section>
      ) : null}
      {social ? (
        <section className="block">
          <h2>Social posts</h2>
          {social.map((p, i) => (
            <article key={`s-${i}`} className="email">
              <h3>{getStr(p, "platform")}</h3>
              <pre className="prose">{getStr(p, "caption")}</pre>
              <p className="muted small">
                {getArr(p, "hashtags")?.map(String).join(" ")}
              </p>
            </article>
          ))}
        </section>
      ) : null}
      {email ? (
        <section className="block">
          <h2>Re-engagement email</h2>
          <p className="subject">Subject: {getStr(email, "subject")}</p>
          <pre className="prose">{getStr(email, "body")}</pre>
          <p className="muted small">Segment: {getStr(email, "segment")}</p>
        </section>
      ) : null}
      {wa ? (
        <section className="block">
          <h2>WhatsApp broadcast</h2>
          <p className="muted small">
            Send to: {getStr(wa, "segmentationCue")}
          </p>
          <pre className="prose">{getStr(wa, "template")}</pre>
          <p className="muted small">
            Opt-out: {getStr(wa, "optInDisclaimer")}
          </p>
        </section>
      ) : null}
      {offer ? (
        <section className="block">
          <h2>Limited-time offer card</h2>
          <h3>{getStr(offer, "headline")}</h3>
          <p>{getStr(offer, "description")}</p>
          <p>
            <strong>{getStr(offer, "priceLabel")}</strong> · valid until{" "}
            {getStr(offer, "validUntilSuggestion")}
          </p>
          <p className="muted">{getStr(offer, "redemptionMechanic")}</p>
        </section>
      ) : null}
    </>
  );
}

function ListingPaper({ output }: { output: unknown }) {
  const listing = getObj(output, "listing");
  const social = getObj(output, "social");
  const email = getObj(output, "buyerEmail");
  const comps = getObj(output, "comps");
  const market = getObj(output, "marketUpdate");
  return (
    <>
      {listing ? (
        <section className="block">
          <h2>{getStr(listing, "headline")}</h2>
          <p className="muted small">
            {getStr(listing, "wordCount")} words · meta:{" "}
            {getStr(listing, "metaSnippet")}
          </p>
          <pre className="prose">{getStr(listing, "body")}</pre>
        </section>
      ) : null}
      {social ? (
        <section className="block">
          <h2>Open-house posts</h2>
          {(["instagram", "facebook"] as const).map((k) => {
            const block = getObj(social, k);
            if (!block) return null;
            return (
              <article key={k} className="email">
                <h3>{k}</h3>
                <pre className="prose">{getStr(block, "caption")}</pre>
                <p className="muted small">
                  {getArr(block, "hashtags")?.map(String).join(" ")}
                </p>
              </article>
            );
          })}
          {getObj(social, "whatsapp") ? (
            <article className="email">
              <h3>WhatsApp broadcast</h3>
              <pre className="prose">
                {getStr(getObj(social, "whatsapp"), "message")}
              </pre>
            </article>
          ) : null}
        </section>
      ) : null}
      {email ? (
        <section className="block">
          <h2>Buyer-list email</h2>
          <p className="subject">Subject: {getStr(email, "subject")}</p>
          <pre className="prose">{getStr(email, "body")}</pre>
          <p className="muted small">Segment: {getStr(email, "segment")}</p>
        </section>
      ) : null}
      {comps ? (
        <section className="block">
          <h2>Comparable analysis</h2>
          <ol>
            {getArr(comps, "comps")?.map((c, i) => (
              <li key={`c-${i}`}>
                <strong>{getStr(c, "descriptor")}</strong> —{" "}
                {getStr(c, "soldOrListed")}.{" "}
                <em>Difference: {getStr(c, "differentiator")}</em>
              </li>
            ))}
          </ol>
          <p>
            <strong>Positioning:</strong> {getStr(comps, "positioningNote")}
          </p>
        </section>
      ) : null}
      {market ? (
        <section className="block">
          <h2>Suburb market update</h2>
          <p className="subject">{getStr(market, "headline")}</p>
          <ul>
            {getArr(market, "bullets")?.map((b, i) => (
              <li key={`mu-${i}`}>{String(b)}</li>
            ))}
          </ul>
          <p className="muted">
            <strong>Voice-note opener:</strong>{" "}
            <em>&ldquo;{getStr(market, "voiceNoteOpener")}&rdquo;</em>
          </p>
        </section>
      ) : null}
    </>
  );
}

const PRINT_STYLES = `
  * { box-sizing: border-box; }
  html, body {
    margin: 0;
    padding: 0;
    background: #fff;
    color: #111;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue",
      Helvetica, Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.55;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  .paper {
    max-width: 820px;
    margin: 0 auto;
    padding: 40pt 32pt;
  }
  .head {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    border-bottom: 1px solid #e5e5e5;
    padding-bottom: 10pt;
    margin-bottom: 24pt;
  }
  .brand {
    font-weight: 700;
    letter-spacing: 0.2em;
    text-transform: uppercase;
    font-size: 10pt;
  }
  .meta {
    font-size: 9pt;
    color: #6b6b6b;
    text-transform: uppercase;
    letter-spacing: 0.1em;
  }
  h1.title {
    font-size: 22pt;
    font-weight: 800;
    line-height: 1.15;
    margin: 0 0 28pt;
    letter-spacing: -0.01em;
  }
  .block {
    page-break-inside: avoid;
    margin-bottom: 24pt;
  }
  h2 {
    font-size: 13pt;
    font-weight: 700;
    margin: 0 0 8pt;
    border-bottom: 1px solid #e5e5e5;
    padding-bottom: 4pt;
  }
  h3 {
    font-size: 11pt;
    font-weight: 700;
    margin: 12pt 0 4pt;
    color: #333;
  }
  p { margin: 4pt 0 8pt; }
  ul, ol { margin: 4pt 0 8pt 18pt; }
  li { margin-bottom: 3pt; }
  .email {
    border-left: 2pt solid #d4d4d4;
    padding: 6pt 12pt;
    margin: 10pt 0;
    background: #fafafa;
  }
  .subject {
    font-weight: 600;
    font-size: 11pt;
    margin-bottom: 4pt;
  }
  .prose {
    font-family: inherit;
    font-size: 10.5pt;
    line-height: 1.55;
    white-space: pre-wrap;
    margin: 4pt 0;
  }
  .prose.mono {
    font-family: "SF Mono", "Menlo", "Monaco", "Consolas", monospace;
    font-size: 9.5pt;
    background: #f5f5f5;
    padding: 6pt 8pt;
    border: 1px solid #e5e5e5;
  }
  .muted {
    color: #6b6b6b;
  }
  .small {
    font-size: 9pt;
  }
  .foot {
    margin-top: 36pt;
    padding-top: 10pt;
    border-top: 1px solid #e5e5e5;
    display: flex;
    justify-content: space-between;
    font-size: 9pt;
    color: #9b9b9b;
    font-family: "SF Mono", "Menlo", "Monaco", monospace;
  }
  @media print {
    .paper { padding: 24pt 18pt; }
    .head, h2, .foot { break-inside: avoid; }
  }
`;
