/**
 * Guardian rule packs — Wave 64 (six packs that reach 32 total and
 * complete the six-continent coverage map):
 *   - NIST AI RMF 600-1 GenAI Profile (US federal voluntary-mandatory)
 *   - China PIPL + CAC GenAI Interim Measures + Deep Synthesis
 *   - Japan APPI + METI AI Guidelines for Business
 *   - South Korea PIPA + AI Basic Act (eff. Jan 2026)
 *   - South Africa POPIA + draft AI National Policy Framework
 *   - UAE PDPL + DIFC AI Regulation + ADGM
 *
 * 18 new rules · ~40 tests · brings ALL_PACKS to 32.
 * Geographic coverage now spans Americas + Europe + APAC + MEA + ISO.
 */
import { describe, it, expect } from "vitest";
import {
  nistAiRmfRules,
  nistAiRmfPack,
  chinaPiplGenAiRules,
  chinaPiplGenAiPack,
  japanAppiRules,
  japanAppiPack,
  koreaPipaRules,
  koreaPipaPack,
  southAfricaPopiaRules,
  southAfricaPopiaPack,
  uaePdplRules,
  uaePdplPack,
  ALL_PACKS,
} from "../src/packs.js";
import type { GuardianRule } from "../src/guardian.js";

function findRule(rules: GuardianRule[], id: string): GuardianRule {
  const r = rules.find((rule) => rule.id === id);
  if (!r) throw new Error(`rule not found: ${id}`);
  return r;
}

async function evalAt(
  rule: GuardianRule,
  output: unknown,
  input: unknown = {},
  extra: Record<string, unknown> = {},
) {
  return rule.evaluate({
    runId: "test-run",
    agentSlug: "test-agent",
    tokenId: "test-tok",
    input,
    output,
    ...extra,
  });
}

describe("NIST AI RMF 600-1 pack — GenAI Profile", () => {
  it("registers in ALL_PACKS with 3 rules + correct citation", () => {
    expect(ALL_PACKS.some((p) => p.id === nistAiRmfPack.id)).toBe(true);
    expect(nistAiRmfPack.rules.length).toBe(3);
    expect(nistAiRmfPack.citation).toMatch(/NIST|600-1/);
  });

  it("WARNS on GenAI output without risk-control ID", async () => {
    const rule = findRule(nistAiRmfRules, "nist-ai-600-risk-control-id");
    const v = await evalAt(rule, "GenAI output: generated summary returned.");
    expect(v.verdict).toBe("warn");
  });

  it("PASSES GenAI output WITH MAP function risk-control ID", async () => {
    const rule = findRule(nistAiRmfRules, "nist-ai-600-risk-control-id");
    const v = await evalAt(
      rule,
      "GenAI output: summary returned. NIST AI 600-1 MAP 3.4 risk-control applied.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on GenAI output without AI RMF function tag", async () => {
    const rule = findRule(nistAiRmfRules, "nist-ai-rmf-function-tag");
    const v = await evalAt(
      rule,
      "LLM output: response generated for client query.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES GenAI output WITH Govern function tag", async () => {
    const rule = findRule(nistAiRmfRules, "nist-ai-rmf-function-tag");
    const v = await evalAt(
      rule,
      "LLM output: response generated. NIST AI RMF Govern function applied per AI 100-1.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on AI-generated content without provenance flag", async () => {
    const rule = findRule(nistAiRmfRules, "nist-ai-provenance-flag");
    const v = await evalAt(
      rule,
      "Foundation model output: image generated by prompt.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES AI-generated content WITH C2PA provenance assertion", async () => {
    const rule = findRule(nistAiRmfRules, "nist-ai-provenance-flag");
    const v = await evalAt(
      rule,
      "Foundation model output: image generated. C2PA assertion attached, content credentials embedded.",
    );
    expect(v.verdict).toBe("pass");
  });
});

describe("China PIPL + GenAI Interim Measures pack", () => {
  it("registers in ALL_PACKS with 3 rules + correct citation", () => {
    expect(ALL_PACKS.some((p) => p.id === chinaPiplGenAiPack.id)).toBe(true);
    expect(chinaPiplGenAiPack.rules.length).toBe(3);
    expect(chinaPiplGenAiPack.citation).toMatch(/PIPL|CAC/);
  });

  it("WARNS on GenAI output without CAC algorithm-filing reference", async () => {
    const rule = findRule(chinaPiplGenAiRules, "cn-genai-algorithm-filing");
    const v = await evalAt(
      rule,
      "Generative AI output: content generation completed.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES GenAI output WITH CAC filing reference", async () => {
    const rule = findRule(chinaPiplGenAiRules, "cn-genai-algorithm-filing");
    const v = await evalAt(
      rule,
      "Generative AI output: content generation completed. CAC algorithm filing CAC-2026-AI-04482 registered.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on PIPL automated decision without Art. 24 disclosure", async () => {
    const rule = findRule(chinaPiplGenAiRules, "cn-pipl-art24-disclosure");
    const v = await evalAt(
      rule,
      "PIPL: automated decision processed for Chinese resident.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES PIPL automated decision WITH Art. 24 disclosure", async () => {
    const rule = findRule(chinaPiplGenAiRules, "cn-pipl-art24-disclosure");
    const v = await evalAt(
      rule,
      "PIPL: automated decision processed for Chinese resident. PIPL Art. 24 transparency disclosure provided.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on synthetic media without Deep Synthesis content mark", async () => {
    const rule = findRule(
      chinaPiplGenAiRules,
      "cn-deep-synthesis-content-mark",
    );
    const v = await evalAt(rule, "Deep synthesis: AI image generated.");
    expect(v.verdict).toBe("warn");
  });

  it("PASSES synthetic media WITH content mark", async () => {
    const rule = findRule(
      chinaPiplGenAiRules,
      "cn-deep-synthesis-content-mark",
    );
    const v = await evalAt(
      rule,
      "Deep synthesis: AI image generated. Synthetic content mark embedded per Deep Synthesis Provisions art. 17.",
    );
    expect(v.verdict).toBe("pass");
  });
});

describe("Japan APPI + METI pack", () => {
  it("registers in ALL_PACKS with 3 rules + correct citation", () => {
    expect(ALL_PACKS.some((p) => p.id === japanAppiPack.id)).toBe(true);
    expect(japanAppiPack.rules.length).toBe(3);
    expect(japanAppiPack.citation).toMatch(/APPI|METI/);
  });

  it("WARNS on Japan AI processing without APPI consent basis", async () => {
    const rule = findRule(japanAppiRules, "jp-appi-consent-basis");
    const v = await evalAt(
      rule,
      "APPI processing: Japanese data subject inference complete.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES Japan AI processing WITH APPI consent", async () => {
    const rule = findRule(japanAppiRules, "jp-appi-consent-basis");
    const v = await evalAt(
      rule,
      "APPI processing: Japanese data subject. APPI Art. 17 consent basis verified, opt-in confirmed.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on Japan AI output without METI guideline tag", async () => {
    const rule = findRule(japanAppiRules, "jp-meti-guideline-applicability");
    const v = await evalAt(
      rule,
      "APPI-scope AI output for Japanese user produced.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES Japan AI output WITH METI guideline applicability", async () => {
    const rule = findRule(japanAppiRules, "jp-meti-guideline-applicability");
    const v = await evalAt(
      rule,
      "APPI-scope AI output for Japanese user. METI AI Guidelines for Business v1.0 applicability tagged.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on Japan-data cross-border transfer without Art. 28 attestation", async () => {
    const rule = findRule(japanAppiRules, "jp-appi-cross-border-attestation");
    const v = await evalAt(
      rule,
      "APPI processing: cross-border inference of Japanese data subject record.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES Japan-data cross-border transfer WITH Art. 28 attestation", async () => {
    const rule = findRule(japanAppiRules, "jp-appi-cross-border-attestation");
    const v = await evalAt(
      rule,
      "APPI processing: cross-border inference. APPI Art. 28 cross-border attestation on file; equivalent protection confirmed.",
    );
    expect(v.verdict).toBe("pass");
  });
});

describe("South Korea PIPA + AI Basic Act pack", () => {
  it("registers in ALL_PACKS with 3 rules + correct citation", () => {
    expect(ALL_PACKS.some((p) => p.id === koreaPipaPack.id)).toBe(true);
    expect(koreaPipaPack.rules.length).toBe(3);
    expect(koreaPipaPack.citation).toMatch(/PIPA|AI Basic Act/);
  });

  it("WARNS on Korean automated decision without PIPA Art. 28-2 consent", async () => {
    const rule = findRule(koreaPipaRules, "kr-pipa-art28-consent");
    const v = await evalAt(
      rule,
      "PIPA: automated decision processed for Korean data subject.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES Korean automated decision WITH PIPA Art. 28-2 reference", async () => {
    const rule = findRule(koreaPipaRules, "kr-pipa-art28-consent");
    const v = await evalAt(
      rule,
      "PIPA: automated decision processed. PIPA Art. 28-2 consent on file, data subject consent verified.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on Korea AI output without AI Basic Act risk-tier tag", async () => {
    const rule = findRule(koreaPipaRules, "kr-ai-basic-act-risk-tier");
    const v = await evalAt(
      rule,
      "PIPA-scope AI inference produced for Korean user.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES Korea AI output WITH risk-tier tag", async () => {
    const rule = findRule(koreaPipaRules, "kr-ai-basic-act-risk-tier");
    const v = await evalAt(
      rule,
      "PIPA-scope AI inference. AI Basic Act risk tier: high-impact AI per Art. 6.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on Korean high-impact decision without right-to-explanation", async () => {
    const rule = findRule(koreaPipaRules, "kr-right-to-explanation");
    const v = await evalAt(
      rule,
      "Korean resident high-impact automated decision processed.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES Korean high-impact decision WITH right-to-explanation", async () => {
    const rule = findRule(koreaPipaRules, "kr-right-to-explanation");
    const v = await evalAt(
      rule,
      "Korean resident high-impact automated decision. Right to explanation notice provided in Korean per AI Basic Act Art. 11.",
    );
    expect(v.verdict).toBe("pass");
  });
});

describe("South Africa POPIA + AI Framework pack", () => {
  it("registers in ALL_PACKS with 3 rules + correct citation", () => {
    expect(ALL_PACKS.some((p) => p.id === southAfricaPopiaPack.id)).toBe(true);
    expect(southAfricaPopiaPack.rules.length).toBe(3);
    expect(southAfricaPopiaPack.citation).toMatch(/POPIA/);
  });

  it("WARNS on SA automated decision without POPIA s. 71 notice", async () => {
    const rule = findRule(
      southAfricaPopiaRules,
      "za-popia-s71-auto-decision-notice",
    );
    const v = await evalAt(
      rule,
      "POPIA: automated decision processed for South African data subject.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES SA automated decision WITH POPIA s. 71 notice", async () => {
    const rule = findRule(
      southAfricaPopiaRules,
      "za-popia-s71-auto-decision-notice",
    );
    const v = await evalAt(
      rule,
      "POPIA: automated decision processed for SA data subject. POPIA s. 71 notice provided, right to representation available.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on high-risk SA AI deployment without IR notification", async () => {
    const rule = findRule(
      southAfricaPopiaRules,
      "za-ai-framework-high-risk-notification",
    );
    const v = await evalAt(
      rule,
      "High-risk AI deployment to South African market: credit scoring engine.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES high-risk SA AI deployment WITH IR notification", async () => {
    const rule = findRule(
      southAfricaPopiaRules,
      "za-ai-framework-high-risk-notification",
    );
    const v = await evalAt(
      rule,
      "High-risk AI deployment: credit scoring engine. Information Regulator notification filed (IR-2026-Q2-AI-441).",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on POPIA AI output without responsible-party attribution", async () => {
    const rule = findRule(
      southAfricaPopiaRules,
      "za-popia-responsible-party-attribution",
    );
    const v = await evalAt(
      rule,
      "POPIA: processing of South African personal information completed.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES POPIA AI output WITH responsible-party attribution", async () => {
    const rule = findRule(
      southAfricaPopiaRules,
      "za-popia-responsible-party-attribution",
    );
    const v = await evalAt(
      rule,
      "POPIA: processing of SA personal information. Responsible party: Sovereign Matrix (Pty) Ltd; data processor identified per POPIA s. 8.",
    );
    expect(v.verdict).toBe("pass");
  });
});

describe("UAE PDPL + DIFC AI pack", () => {
  it("registers in ALL_PACKS with 3 rules + correct citation", () => {
    expect(ALL_PACKS.some((p) => p.id === uaePdplPack.id)).toBe(true);
    expect(uaePdplPack.rules.length).toBe(3);
    expect(uaePdplPack.citation).toMatch(/UAE|PDPL|DIFC/);
  });

  it("WARNS on UAE automated decision without PDPL Art. 13 notice", async () => {
    const rule = findRule(uaePdplRules, "ae-pdpl-art13-auto-decision-notice");
    const v = await evalAt(
      rule,
      "UAE PDPL: automated decision processed for Emirati resident.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES UAE automated decision WITH PDPL Art. 13 notice", async () => {
    const rule = findRule(uaePdplRules, "ae-pdpl-art13-auto-decision-notice");
    const v = await evalAt(
      rule,
      "UAE PDPL: automated decision processed for Emirati resident. PDPL Art. 13 notice + right to object provided.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on DIFC-scope AI output without risk-tier tag", async () => {
    const rule = findRule(uaePdplRules, "ae-difc-ai-risk-tier");
    const v = await evalAt(
      rule,
      "UAE PDPL: DIFC financial-zone AI inference produced.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES DIFC-scope AI output WITH risk-tier tag", async () => {
    const rule = findRule(uaePdplRules, "ae-difc-ai-risk-tier");
    const v = await evalAt(
      rule,
      "UAE PDPL: DIFC financial-zone AI inference. DIFC AI risk tier tagged: moderate per consultation framework.",
    );
    expect(v.verdict).toBe("pass");
  });

  it("WARNS on UAE high-stakes decision without Arabic right-to-review", async () => {
    const rule = findRule(uaePdplRules, "ae-arabic-right-to-review");
    const v = await evalAt(
      rule,
      "UAE PDPL: high-stakes credit denial automated decision for Emirati resident.",
    );
    expect(v.verdict).toBe("warn");
  });

  it("PASSES UAE high-stakes decision WITH Arabic right-to-review", async () => {
    const rule = findRule(uaePdplRules, "ae-arabic-right-to-review");
    const v = await evalAt(
      rule,
      "UAE PDPL: high-stakes credit denial for Emirati resident. Bilingual notice: Arabic-language right-to-review provided.",
    );
    expect(v.verdict).toBe("pass");
  });
});

describe("Composition — Wave 64 brings total to 32 packs across 6 continents", () => {
  it("ALL_PACKS includes all 6 new Wave-64 packs", () => {
    const ids = ALL_PACKS.map((p) => p.id);
    expect(ids).toContain(nistAiRmfPack.id);
    expect(ids).toContain(chinaPiplGenAiPack.id);
    expect(ids).toContain(japanAppiPack.id);
    expect(ids).toContain(koreaPipaPack.id);
    expect(ids).toContain(southAfricaPopiaPack.id);
    expect(ids).toContain(uaePdplPack.id);
  });

  it("ALL_PACKS has ≥ 32 packs (compounding compliance moat)", () => {
    expect(ALL_PACKS.length).toBeGreaterThanOrEqual(32);
  });

  it("every Wave-64 rule has a unique id", () => {
    const ids = new Set<string>();
    const wave64 = [
      ...nistAiRmfRules,
      ...chinaPiplGenAiRules,
      ...japanAppiRules,
      ...koreaPipaRules,
      ...southAfricaPopiaRules,
      ...uaePdplRules,
    ];
    for (const r of wave64) {
      expect(ids.has(r.id)).toBe(false);
      ids.add(r.id);
    }
    expect(wave64.length).toBe(18);
  });
});
