"use client";

import React, { useState } from "react";
import { Copy, Download, Check, FileText } from "lucide-react";

interface ExportButtonsProps {
  content: string;
  filename?: string;
  className?: string;
}

/**
 * Reusable export buttons for all AI tool results.
 * Copy to clipboard + Download as .txt file.
 */
export function ExportButtons({
  content,
  filename = "umbra-output",
  className = "",
}: ExportButtonsProps) {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = content;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const downloadAsText = () => {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${filename}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const downloadAsHTML = () => {
    // Convert markdown-like content to basic HTML
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${filename}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #333; }
    h1, h2, h3 { color: #111; } pre { background: #f5f5f5; padding: 16px; border-radius: 8px; overflow-x: auto; }
    .generated-by { color: #999; font-size: 12px; text-align: center; margin-top: 40px; border-top: 1px solid #eee; padding-top: 20px; }
  </style>
</head>
<body>
  <div>${content.replace(/\n/g, "<br>")}</div>
  <p class="generated-by">Generated by SOVEREIGN — AI Marketing Platform</p>
</body>
</html>`;
    const blob = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${filename}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (!content) return null;

  return (
    <div className={`flex items-center gap-2 ${className}`}>
      <button
        onClick={copyToClipboard}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-white/10 bg-white/[0.03] text-xs font-bold text-neutral-400 hover:text-white hover:border-emerald-500/30 hover:bg-emerald-500/5 transition-gpu uppercase tracking-wider focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500/40 focus-visible:ring-offset-2 focus-visible:ring-offset-black"
        title="Copy to clipboard"
      >
        {copied ? (
          <Check className="w-3 h-3 text-emerald-400" />
        ) : (
          <Copy className="w-3 h-3" />
        )}
        {copied ? "Copied" : "Copy"}
      </button>
      <button
        onClick={downloadAsText}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-white/10 bg-white/[0.03] text-xs font-bold text-neutral-400 hover:text-white hover:border-[#00B7FF]/30 hover:bg-[#00B7FF]/5 transition-gpu uppercase tracking-wider focus:outline-none focus-visible:ring-2 focus-visible:ring-[#00B7FF]/40 focus-visible:ring-offset-2 focus-visible:ring-offset-black"
        title="Download as text file"
      >
        <Download className="w-3 h-3" />
        .TXT
      </button>
      <button
        onClick={downloadAsHTML}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-white/10 bg-white/[0.03] text-xs font-bold text-neutral-400 hover:text-white hover:border-purple-500/30 hover:bg-purple-500/5 transition-gpu uppercase tracking-wider focus:outline-none focus-visible:ring-2 focus-visible:ring-purple-500/40 focus-visible:ring-offset-2 focus-visible:ring-offset-black"
        title="Download as HTML file"
      >
        <FileText className="w-3 h-3" />
        .HTML
      </button>
    </div>
  );
}
